## Bibliography {#bibliography .Chapter-Heading}

Arntzenius, Frank and David McCarthy (1997) "The Two-Envelope Paradox and Infinite Expectations" *Analysis* 47: 42‑50.

Arrow, Kenneth (1963) *Social Choice and Individual Values*. New York: Wiley.

Ayer, Alfred (1936) *Language, Truth and Logic*. London: Gollantz. Second edition 1947. References to second edition.

Ayer, Alfred (1957) The Conception of Probability as a Logical Relation. Reprinted in his *The Concept of a Person*, London: Macmillan Press, 1963, pp 188 - 198.

Bacchus, Fahiem, Henry Kyburg and Mariam Thalos (1990) "Against Conditionalisation" *Synthese* 85: 475 ‑ 506.

Barker, Stephen (1995) "Towards a Pragmatic Theory of 'If'" *Philosophical Studies* 79: 185‑211.

Bateman, Brad (1996) *Keynes's Uncertain Revolution*. Ann Arbor: University of Michigan Press.

Bertrand, Jean (1889) *Calcul des Probabilités*. Paris: Gauthier-Villars. First English edition 1972.

Bigelow, John and Robert Pargetter (1990) *Science and Necessity*. Cambridge: Cambridge University Press.

Bigelow, John, John Collins and Robert Pargetter (1993) "The Big Bad Bug: What are the Humean's Chances" *British Journal for the Philosophy of Science* 44: 443‑462.

Black, Max (1967) "Probability" in Paul Edwards *et al* (eds) *The Encyclopaedia of Philosophy*, New York: Macmillan, 8 vols., vol. 6, pp 464‑479.

Blackburn, Simon (1980) "Opinions and Chances" in Mellor (ed), pp 175‑196.

Blackburn, Simon (1984) *Spreading the Word*. Oxford: Clarendon Press.

Blackburn, Simon (1988) "Attitudes and Contents" *Ethics* 98: 501‑517.

Borel, Emile (1924) "A propos d'un Traité de Probabilités" *Revue Philosophique* 98: 321-336. English translation in Kyburg and Smokler (eds) (1964), pp 45‑60.

Broome, John (1995) "The Two-Envelope Paradox" *Analysis* 55: 6‑11.

Carnap, Rudolf (1945) The Two Concepts of Probability. *Philosophy and Phenomenological Research* 5: 513 ‑ 532.

Carnap, Rudolf (1950) *Logical Foundations of Probability*. Chicago: University of Chicago Press. Second Edition 1962. References to second edition.

Carnap, Rudolf (1952) *The Continuum of Inductive Methods*. Chicago: University of Chicago Press.

Carnap, Rudolf (1963) "Replies and Systematic Expositions" in Paul Schilpp (ed) *The Philosophy of Rudolf Carnap*. Illinois: Open Court, pp 859‑1016.

Carnap, Rudolf (1971) Inductive Logic and Rational Decisions. In R. Carnap and R. C. Jeffery (eds) *Studies in Inductive Logic and Probability* Vol. 1, Berkeley: University of California Press, pp 5 ‑ 32.

Carroll, Lewis (1871) *Through the Looking Glass, and What Alice Found There*. London: Macmillan. Reprinted in *The Annotated Alice*, edited by Martin Gardner, London: Penguin 1960. References to reprint.

Chisolm, Roderick (1989) "Probability in the Theory of Knowledge" in Marjorie Clay and Keith Lehrer (eds) *Knowledge and Skepticism*. Boulder: Westview.

Christensen, David (1996) "Dutch-Book Arguments De-Pragmatized" *Journal of Philosophy* 93: 450 ‑ 479.

Coates, John (1996) *The Claims of Common Sense*. Cambridge: Cambridge University Press.

Cohen, L. J. (1977) *The Probable and the Provable*. Oxford: Clarendon Press.

Davidson, Barbara and Robert Pargetter (1985) "In Defence of the Dutch Book Argument" *Canadian Journal of Philosophy* 15: 405 ‑ 424.

Davidson, Paul (1988) "A Technical Definition of Uncertainty and the Long-Run Non-neutrality of Money" *Cambridge Journal of Economics* 12: 329‑338.

Davidson, Paul (1991) "Is Probability Theory Relevant for Uncertainty? A Post Keynesian Perspective" *Journal of Economic Perspectives* 5: 129‑144.

Davidson, Paul (1994) *Post Keynesian Macroeconomic Theory*. Aldershot: Edward Elgar.

Davis, John (1994) *Keynes's Philosophical Development*. Cambridge: Cambridge University Press.

de Finetti, Bruno (1937) "La Prévision; ses lois logiques, ses sources subjectives" *Annales de l'Institute Henri Poincaré* 7: 1‑68. First English translation in Kyburg and Smokler (eds) (1964), pp 93‑158. References to translation.

de Finetti, Bruno (1972) *Probability, Induction and Statistics*. New York: Wiley.

de Finetti, Bruno (1974) *Theory of Probability*. London: Wiley.

Dempster, Arthur (1967) "Upper and Lower Probabilities induced by a Multi-valued Mapping" *Annals of Mathematical Statistics* 38: 325‑339.

Dempster, Arthur (1968) "A Generalisation of Bayesian Inference" *Journal of the Royal Statistical Society Series* B 30: 205‑247.

Dempster, Arthur (1988) "Probability, Evidence and Judgment" (with discussion) in D. Bell, H. Raiffa and A. Tversky (eds) *Decision Making*. Cambridge: Cambridge University Press. pp 283‑298.

Dummett, Michael (1959) "Truth" *Proceedings of the Aristotelian Society* 59: 141-62. Reprinted in his *Truth and Other Enigmas*, London: Duckworth, 1978, pp 1 ‑ 19. References to reprint.

Dummett, Michael (1975) "Wang's Paradox" *Synthese* 30: 301‑324.

Dummett, Michael (1977) *Elements of Intuitionism*. Oxford: Clarendon Press.

Edwards, W. H. Lindman and L. J. Savage (1963) "Bayesian Statistical Inference for Psychological Research" *Psychological Review* 70: 193‑242.

Fagin, R. and J. Halpern (1991). A New Approach to Updating Beliefs. In P. Bonissone, M. Henrion, L. Kanal and J. Lemmer (eds) *Uncertainty in Artificial Intelligence 6*. Amsterdam: North‑Holland, pp 347‑374.

Fine, Kit (1975) "Vagueness, Truth and Logic" *Synthese* 30: 265-300.

Fine, Terrence (1973) *Theories of Probability: An Examination of Foundations*. New York: Academic Press.

Fine, Terrence (1983) "Foundations of Probability" in S. Kotz and N. L. Johnson (eds.) *The Encyclopaedia of Statistical Sciences* Vol. 3, New York: Wiley.

Fodor, Jerry and Ernest Lepore (1996) "What Cannot be Valuated Cannot be Valuated, and it Cannot be Supervaluated Either" *Journal of Philosophy* 93: 516‑535.

Friedman, Milton and Leonard Savage (1952) "The Expected Utility Hypothesis and the Measurability of Utility" *Journal of Political Economy* 60: 463‑474.

Gardner, Martin (1961) *The Second Scientific American Book of Mathematical Puzzles and Diversions*. New York: Simon & Schuster.

Geach, Peter (1965) "Assertion" *Philosophical Review* 74: 449‑465.

Gibbard, Alan (1990) *Wise Choices*, *Apt Feelings*. Oxford: Clarendon Press.

Gilboa, Itzhak and David Schmeidler (1993) "Updating Ambiguous Beliefs" *Journal of Economic Theory* 59: 33‑49.

Gillies, Donald (1988) "Keynes as a Methodologist" *British Journal for the Philosophy of Science* 39: 117‑29.

Gillies, Donald (1991) "Intersubjective Probability and Confirmation Theory" *British Journal for Philosophy of Science* 42: 513- 533.

Gillman, Leonard (1992) "The Car and the Goats" *American Mathematical Monthly* 99: 3‑8.

Gödel, Kurt (1931) "Über Formal Unentscheidbare Sätze der *Principia Mathematica* und Verwandter Systeme, I" *Monatshefte für Mathematik und Physik* 38: 173‑198.

Good, I. J. (1950) *Probability and the Weighing of Evidence*. London: Griffin.

Good, I. J. (1952) "Rational Decisions" *Journal of the Royal Statistical Society* Series B 14, 107 ‑ 114. Reprinted in his *Good Thinking*, Minneapolis: University of Minnesota Press, 1983, pp 3 ‑ 14.

Good, I. J. (1962) "Subjective Probability as the Measure of a Non-Measurable Set" in E. Nagel, P. Suppes and A. Tarski (eds.) *Logic, Methodology and Philosophy of Science*. Stanford: Stanford University Press, pp 319‑329.

Goodman, Nelson (1947) "The Problem of Counterfactual Conditionals" *Journal of Philosophy* 44: 113‑128.

Goodman, Nelson (1954) *Fact, Fiction and Forecast*. Cambridge, MA.: Harvard University Press.

Green, Mitchell and Christopher Hitchcock (1994) "Reflections on Reflection: van Fraassen on Belief" *Synthese* 98: 297‑324.

Hacking, Ian (1975) *The Emergence of Probability*. Cambridge: Cambridge University Press.

Hájek, Alan (1998?) "Objecting Vaguely to Pascal's Wager" To be published?

Hale, Bob (1993) "Can There be a Logic of Attitudes" in John Haldane and Crispin Wright (eds) *Reality, Representation and Projection*. New York: Oxford University Press, pp 337‑364.

Hall, Ned (1994) Correcting the Guide to Objective Chance. *Mind* 103: 504 ‑ 517.

Hammond, Peter (1988) "Consequentialist Foundations for Expected Utility Theory" *Theory and Decision* 25: 25‑78.

Hansson, Bengt (1988) "Risk Aversion as a Problem of Conjoint Measurement" in P. Gärdenfors and N. E. Sahlin (eds.) *Decision, Probability and Utility*. Campbridge: Cambridge University Press, pp 117‑136.

Harcourt, Geoff and P. A. Riach (1997) *A 'Second Edition' of the General Theory*. 2 Vols. London: Routledge.

Harman, Gilbert (1983) "Problems with Probabilistic Semantics" In A. Orenstein and R. Stern (eds) *Developments in Semantics*, New York: Haven, pp 243 ‑ 247.

Hart, A. G. (1942) "Risk, Uncertainty and the Unprofitability of Compounding Probabilities" in O. Lange, F. McIntyre and T. O. Yntema (eds) *Studies in Mathematical Economics and Econometrics*. Chicago: University of Chicago Press.

Hausman, Daniel (1991) *The Inexact and Separate Science of Economics*. Cambridge: Cambridge University Press.

Hellman, Geoffrey (1997) "Bayes and Beyond" *Philosophy of Science* 64: 191‑221.

Hempel, Carl (1965) *Aspects of Scientific Explanation*. New York: Free Press.

Hicks, John (1967) *Critical Essays in Monetary Theory*. Oxford: Clarendon Press.

Horgan, Terence (1995) "Let's Make a Deal" *Philosophical Papers* 24: 209‑225.

Horwich, Paul (1994) "The Essence of Expressivism" *Analysis* 54: 19‑20.

Howson, Colin (1993) "Dutch Book Arguments and Consistency" *Proceedings of the Philosophy of Science Association* 2: 161‑168.

Howson, Colin and Peter Urbach (1989) *Scientific Reasoning*. La Salle: Open Court.

Jackson, Frank and Robert Pargetter (1976) "A Modified Dutch Book Argument" *Philosophical Studies* 29, 403 ‑ 407.

Jaffray, J. (1994) Decision Making with Belief Functions. In Yager, Fedrizzi and Kacpzyk (eds) pp. 331‑352.

Jeffrey, Richard (1983a) "Bayesianism with a Human Face", in J. Earman (ed.) *Testing Scientific Theories*, Minneapolis: University of Minnesota Press.

Jeffrey, Richard (1983b) *The Logic of Decision*. Chicago: University of Chicago Press, second edition. First edition New York: McGraw Hill, 1965.

Jeffrey, Richard (1987) "Indefinite Probabilities: Reply to Levi" *Philosophy of Science* 54: 587‑591.

Jeffrey, Richard (1991) "Radical Probabilism" in Enrique Villanueva (ed) *Rationality in Epistemology*. Atascadero: Ridgeview.

Jeffrey, Richard (1992) *Probability and the Art of Judgement*. Cambridge: Cambridge University Press.

Jones, R. and J. M. Ostroy (1984) "Flexibility and Uncertainty" *Review of Economic Studies* 51: 13‑32.

Kahnemann, Daniel and Amos Tversky (1979) "Prospect Theory: An Analysis of Decision Under Risk" *Econometrica* 47: 263 ‑ 291.

Kaplan, Mark (1996) *Decision Theory as Philosophy*. Cambridge: Cambridge University Press.

Keynes, John Maynard (1910) "Great Britain's Foreign Investments" *New Quarterly* February (1910); *C*.*W*. XV 46-7

Keynes, John Maynard (1921a) *Treatise on Probability*. London: Macmillan; *C*.*W*. VIII.

Keynes, John Maynard (1921b) "The State and Finance"; *C*. *W*. XVI 295‑307.

Keynes, John Maynard (1931) Review of *Foundations of Mathematics* by Frank Ramsey, *The New Statesman and Nation* 2: 407; *C*.*W*. X: 336-9.

Keynes, John Maynard (1936) *The General Theory of Employment, Interest and Money*. London: Macmillan; *C*.*W*. VII.

Keynes, John Maynard (1937a) "The General Theory of Employment", *Quarterly Journal of Economics* 51: 209‑23; *C*.*W*. XIV 109-23.

Keynes, John Maynard (1937b) "The 'Ex Ante' Theory of the Rate of Interest" *Economic Journal* 47: 663‑668. *C*. *W*. XIV 215‑223.

Keynes, John Maynard (1938a) Letter to Hugh Townshend dated 27 July. *C*.*W*. XIV 288‑9.

Keynes, John Maynard (1938b) Letter to Hugh Townshend dated 7 December. *C*.*W*. XIV 293‑4.

Keynes, John Maynard (1938c) "My Early Beliefs"; *C*. *W*. X: 433‑450.

Keynes, John Maynard (1971-89) *The Collected Writings of John Maynard Keynes* \[*C*.*W*.\] ed. D.E. Moggridge, Vols I ‑ XXX, London: Macmillan. (All references to the *C*.*W*. reprints).

Knight, Frank (1921) *Risk, Uncertainty and Profit*. Chicago: University of Chicago Press.

Kolmogorov, A. N. (1933) *Foundations of the Theory of Probability*. First English edition New York: Chelsea Publishing Company, 1950. References to 1950 edition.

Koopman, Bernard (1940) "The Bases of Probability" *Bulletin of the American Mathematical Society* 46: 763‑774.

Kripke, Saul (1965) "Semantical Analysis of Intuitionistic Logic, I" in M. Dummett and J. Crossley (eds.) *Formal Systems and Recursive Functions*. Amsterdam: North-Holland.

Kripke, Saul (1972) "Naming and Necessity" In Donald Davidson and Gilbert Harman (eds) *Semantics of Natural Language*. Dordrecht: Reidel.

Kripke, Saul (1975) "Outline of a Theory of Truth" *Journal of Philosophy* 72: 690‑716.

Kripke, Saul (1982) *Wittgenstein on Rules and Private Language*, Oxford: Blackwell.

Kvanvig, J. (1994) "A Critique of Van Fraassen's Voluntaristic Epistemology" *Synthese* 98: 325 ‑ 348.

Kyburg, Henry (1961) *Probability and the Logic of Rational Belief*. Middletown: Wesleyan University Press.

Kyburg, Henry (1968) "Bets and Beliefs" *American Philosophical Quarterly* 5: 54‑63. Reprinted in his (1983b) pp 63‑78. References to reprint.

Kyburg, Henry (1974) *The Logical Foundations of Statistical Inference*. Dordrecht: Reidel.

Kyburg, Henry (1978) "Subjective Probability: Criticisms, Reflections and Problems" *Journal of Philosophical Logic* 7: 157‑180. Reprinted in his (1983b), pp 79‑98. References to reprint.

Kyburg, Henry (1983a) "The Reference Class" *Philosophy of Science* 50: 374‑397.

Kyburg, Henry (1983b) *Epistemology and Inference*. Minneapolis: University of Minnesota Press.

Kyburg, Henry (1990) *Science and Reason* New York: Oxford.

Kyburg, Henry and E. Smokler (eds) (1964) *Studies in Subjective Probability*. Huntington: Krieger.

Lawson, Tony (1985) "Uncertainty and Economic Analysis" *Economic Journal* 95: 909‑927.

Levi, Isaac (1974) "On Indeterminate Probabilities" *Journal of Philosophy* 71: 391-418.

Levi, Isaac (1980) *The Enterprise of Knowledge*. Cambridge, MA.: MIT Press.

Levi, Isaac (1986) *Hard Choices*. Cambridge: Cambridge University Press.

Levi, Isaac. (1987) "The Demons of Decision" *Monist* 70: 193 ‑ 211.

Lewis, David (1976a) "The Paradoxes of Time Travel" *American Philosophical Quarterly* 13: 145‑152.

Lewis, David (1976b) "Probability of Conditionals and Conditional Probability" *Philosophical Review* 85: 297‑315.

Lewis, David (1979a) "Scorekeeping in a Language Game" *Journal of Philosophical Logic* 8: 339 ‑ 359. Reprinted in his (1983), pp 233 ‑ 249.

Lewis, David (1979b) "Attitudes *De Dicto* and *De Se*" *Philosophical Review* 88: 513 ‑ 543.

Lewis, David (1980) "A Subjectivist's Guide to Objective Chance" In R. C. Jeffeey (ed) *Studies in Inductive Logic and Probability* Vol. 2, Berkeley: University of California Press, Reprinted with additional postscripts in his (1986b), pp 83 ‑ 132.

Lewis, David (1981) "Causal Decision Theory" *Australasian Journal of Philosophy* 59: 5‑30.

Lewis, David (1986a) "Probabilities of Conditionals and Conditional Probabilities" *Philosophical Review* 95: 581‑589.

Lewis, David (1986b) *Philosophical Papers* Vol. 2, New York: Oxford University Press.

Lewis, David (1988) "Desire as Belief" *Mind* 97: 323‑332.

Lewis, David (1994) "Humean Supervenience Debugged" *Mind* 103: 473 ‑ 490.

Lewis, David (1996) "Elusive Knowledge" *Australasian Journal of Philosophy* 74: 549 ‑567.

Lewis, David (1997) "Finkish Dispositions" *Philosophical Quarterly* 47, 143 ‑ 158.

Lowe, E J (1996) "Conditional Probability and Conditional Beliefs" *Mind*: 105, 603 ‑ 615.

Maclachlan, Fiona (1993) *Keynes's General Theory of Interest: A Reconsideration*. London: Routledge.

Maher, Patrick (1992) "Diachronic Rationality" *Philosophy of Science* 59: 120 ‑ 141.

Maher, Patrick (1993) *Betting on Theories*. Cambridge: Cambridge University Press.

Maher, Patrick (1997) "Depragmatised Dutch Book Arguments" *Philosophy of Science* 64: 291‑305.

Makowski, Louis (1989) "Keynes's Liquidity Preference Theory: A Suggested Reinterpretation" in Frank Hahn (ed) *The Economics of Missing Markets, Information and Games*. Oxford: Clarendon Press.

Martin, C. B. (1994) "Dispositions and Conditionals" *Philosophical Quarterly* 44: 1 ‑ 8.

McCauley, James (1993) *Everything Linguists Have Ever Wanted to Know About Logic* (*But Were Afraid to Ask*) Chicago: University of Chicago Press. Second edition. First edition 1981.

McDermott, Michael (1996) "On the Truth-Conditions of Certain 'If'-Sentences" *Philosophical Review* 105: 1‑37.

Mellor, Hugh (ed) (1980) *Prospects for Pragmatism*. Cambridge: Cambridge University Press.

Morgan, Charles and Edward Mares (1995) "Conditionals, Probability and Non-Triviality" *Journal of Philosophical Logic* 24: 455‑467.

Morgan, Charles and Hughes Leblanc (1983a) "Probabilistic Semantics for Formal Logic" *Notre Dame Journal of Formal Logic* 24: 161‑180.

Morgan, Charles and Hughes Leblanc (1983b) "Probability Theory, Intuitionism, Semantics and the Dutch Book Argument" *Notre Dame Journal of Formal Logic* 24: 289‑304.

Moser, Paul and D. Hudson Mulder (1994) "Probability in Rational Decision-Making" *Philosophical Papers* 23: 109‑128.

Nolan, Daniel (1997) "Quantitative Parsimony" *British Journal for the Philosophy of Science* 48: 329‑342.

Norton, John (1998) "When the Sum of Our Expectations Fails Us" *Pacific Philosophical Quarterly* 79: 34‑58.

O'Donnell, Rod (1989) *Keynes: Philosophy, Economics and Politics*. London: Macmillan Press.

O'Donnell, Rod (1991) "Keynes on Probability, Expectations and Uncertainty" in O'Donnell (ed) (1991) *Keynes as Philosopher - Economist* London: Macmillan, pp 3‑60.

Paris, J. B. (1994) *The Uncertain Reasoner's Companion*. Cambridge: Cambridge University Press.

Pearl, Judea (1988) *Probabilistic Reasoning in Intelligent Systems: Networks of Plausible Inference*. San Mateo: Morgan Kaufman.

Ponsonnet, Jean-Marc (1996) "The Best and the Worst in G. L. S. Shackle's Decision Theory" in Schmidt (ed) 169‑196.

Popper, Karl (1933) *Logic of Scientific Discovery*. London: Routledge. First English edition 1959.

Popper, Karl (1959) "The Propensity Interpretation of Probability" *British Journal for the Philosophy of Science* 10: 25‑42.

Price, Huw (1984) "Mellor, Chance and the Single Case" *British Journal for the Philosophy of Science* 35: 11‑23.

Raiffa, H. (1968) *Decision Analysis: Introductory Lectures on Choice Under Uncertainty*. Reading, MA.: Addison-Wesley.

Ramsey, Frank (1926a) "The Foundations of Mathematics" in his (1931), pp 62‑81.

Ramsey, Frank (1926b) "Truth and Probability" in his (1931), pp 156-198.

Ramsey, Frank (1928) "Chance" in his (1931), pp 206 ‑ 211.

Ramsey, Frank (1929a) "Theories" in his (1931), pp 212‑236.

Ramsey, Frank (1929b) "Probability and Partial Belief" in his (1931), pp 256-7.

Ramsey, Frank (1931) *The Foundations of Mathematics*. Edited by R. B. Braithwaite, London: Routledge.

Rogers, Colin and T. K. Rymes (1997) "Keynes's Monetary Theory of Value and Modern Banking" in Harcourt and Riach (eds), vol. 1, pp 304‑323.

Runde, Jochen (1990) "Keynesian Uncertainty and the Weight of Arguments" *Economics and Philosophy* 6: 275‑93.

Runde, Jochen (1994a) "Keynes After Ramsey: In Defence of 'A Treatise on Probability'" *Studies in the History and Philosophy of Science* 25: 97‑124.

Runde, Jochen (1994b) "Keynesian Uncertainty and Liquidity Preference" *Cambridge Journal of Economics* 18: 129‑144.

Russell, Bertrand (1905) "On Denoting" *Mind* 14: 479‑493.

Russell, Bertrand (1922) "Review of John Maynard Keynes, *A Treatise on Probability*" *Mathematical Gazette* 11: 119‑125.

Russell, Bertrand (1923) "Vagueness" *Australiasian Journal for Psychology and Philosophy* 1, 84‑92.

Russell, Bertrand (1940) *An Inquiry Into Meaning and Truth*. London: Allen and Unwin.

Russell, Bertrand (1948) *Human Knowledge: Its Scope and Limits*. London: Allen and Unwin.

Sainsbury, Mark (1988) *Paradoxes*. Cambridge: Cambridge University Press.

Saul, Jennifer (1997) "Substitution and Simple Sentences" *Analysis*, 57: 102 ‑ 109.

Savage, Leonard (1954) *The Foundations of Statistics*. New York: John Wiley.

Savage, Leonard (1964) "The Foundations of Statistics Reconsidered" In Kyburg and Smokler (eds) (1964), pp 173‑188.

Savage, Leonard (1967a) "Difficulties in the Theory of Personal Probability" *Philosophy of Science* 34: 305‑310.

Savage, Leonard (1967b) "Implications of Personal Probability for Induction" *Journal of Philosophy* 64: 593‑607.

Schick, Frederick (1986) "Dutch Bookies and Money Pumps" *Journal of Philosophy* 83, 112 ‑ 119.

Schmeidler, David (1989) "Subjective Probability and Expected Utility Without Additivity" *Econometrica* 57: 571‑589.

Schmidt, Christian (ed) (1996) *Uncertainty in Economic Thought*, Cheltham, Edward Elgar.

Scott, Alexander and Michael Scott (1997) "What's In the Two-Envelope Paradox" *Analysis* 57: 34‑41.

Seidenfeld, Teddy (1984) Review of Paul Horwich's *Probability and Evidence*. *Philosophical Review* 93 474‑483.

Seidenfeld, Teddy (1994) "When Normal and Extensive Form Decisions Differ" in *Logic, Methodology and Philosophy of Science*, edited by Dag Prawitz, Brian Skyrms and Dag Westerståhl, Amsterdam: Elsevier, pp 451‑463.

Shackle, George (1949) *Expectation in Economics*. Cambridge: Cambridge University Press.

Shackle, George (1961) *Decision, Order and Time in Human Affairs*. Cambridge: Cambridge University Press.

Shackle, George (1972) *Epistemics and Economics: A Critique of Economic Doctrines*. Cambridge: Cambridge University Press.

Shafer, Glenn (1976) *A Mathematical Theory of Evidence*. Princeton: Princeton University Press.

Shafer, Glenn (1981) "Constructive Probability" *Synthese* 48: 1 ‑ 60.

Shapiro, Nina (1997) "Imperfect Competition and Keynes" in Harcourt and Riach (eds), vol. 1, pp 83‑92.

Skidelsky, Robert (1983) *John Maynard Keynes*. Vol. I: *Hopes Betrayed, 1883*-*1920*. London: Macmillan.

Skidelsky, Robert (1992) *John Maynard Keynes*. Vol. II: *The Economist as Saviour, 1920*-*1937*. London: Macmillan.

Slutsky, E. (1915) "On the Theory of the Budget of the Consumer" *Giornale delgi Economisti* 51: 1 ‑ 26. Translated in K. Boulding and G. Stigler (eds.) *Readings in Price Theory* Chicago: Irwin, pp. 27‑56.

Smets, Phillippe (1994) "What is Dempster-Shafer's Theory of Evidence?" In Yager, Fedrizzi and Kacpzyk (eds) pp 5‑34.

Smith, Cedric A. B. (1961) "Consistency in Statistical Inference and Decision" *Journal of the Royal Statistical Society* Series B 23: 1 ‑ 37.

Sobel, J. Howard (1989) "Utility Theory and the Bayesian Paradigm" *Theory and Decision* 26: 263‑293.

Strat, T. (1990) "Decision analysis using Belief Functions" *International Journal of Approximative Reasoning* 4: 391‑417.

Strawson, Peter (1950) "On Referring" *Mind* 59: 320‑344.

Strevens, Michael (1995) "A Closer Look at the 'New' Principle" *British Journal for the Philosophy of Science* 46: 545 ‑ 561.

Suppes, Patrick (1974) "The Measurement of Belief" *Journal of the Royal Statistical Society* Series B 36: 160‑191.

Teller, Paul (1973) "Conditionalization and Observation" *Synthese* 26: 218 ‑ 258.

Thau, Michael (1994) "Undermining and Admissibility" *Mind* 103: 491 ‑ 503.

Tintner, Gerhard (1941) "The Theory of Choice Under Subjective Risk and Uncertainty" *Econometrica* 9: 298‑304.

Tobin, James (1958) "Liquidity Preference as Behaviour Towards Risk" *Review of Economic Studies* 25: 65‑86.

Tooley, Michael (1987) *Causation: A Realist Approach*. Oxford: Oxford University Press.

van Fraassen, Bas (1966) "Singular Terms, Truth‑Value Gaps and Free Logic" *Journal of Philosophy* 66: 481-95.

van Fraassen, Bas (1984) "Belief and the Will" *Journal of Philosophy* 81: 235 ‑ 256.

van Fraassen, Bas (1989) *Laws and Symmetry*. Oxford: Clarendon Press.

van Fraassen, Bas (1990) "Figures in a Probability Landscape" in J. Dunn and A. Gupta (eds) *Truth or Consequences*. Amsterdam: Kluwer, pp 345‑356.

van Fraassen, Bas (1995) "Belief and the Problem of Ulyssess and the Sirens" *Philosophical Studies* 77: 7 - 37.

von Kries, J. (1886) *Die Principien der Wahrscheinlichkeitsrechnung. Eine logische Untersuchung*. Frieburg.

Walley, Peter (1991) *Statistical Reasoning with Imprecise Probabilities* London: Chapman & Hall.

Wang, Hao (1987) *Reflections on Gödel*. Cambridge, MA: MIT Press.

Williams, Peter (1976) Indeterminate Probabilities. In M. Przelecki, K. Szaniawski and R. Wojcicki (eds) *Formal Methods in the Methodology of the Empriccal Sciences*. Dordrecht: Reidel, pp 229‑246.

Williams, Peter (1978) "On a New Theory of Epistemic Probability" *British Journal for the Philosophy of Science* 29: 375‑387.

Williamson, Timothy (1994) *Vagueness*. London: Routledge.

Wittgenstein, Ludwig (1953) *Philosophical Investigations*. London: Routledge.

Wolfenson, Marco and Terrence Fine (1982) "Bayes-Like Decision Making with Upper and Lower Probabilities" *Journal of the American Statistical Society* 72: 80‑88.

Yager, R. , M. Fedrizzi and J. Kacprzyk (eds) (1994) *Advances in the Dempster-Shafer Theory of Evidence*. New York, NY.: John Wiley.

Zabell, S. L. (1991) "Ramsey, Truth and Probability" *Theoria* 57: 211‑238.

Zadeh, Lofti (1978) "Fuzzy Sets as a Basis for a Theory of Probability" *Fuzzy Sets and Systems* 1: 3‑28.

##  {#section .Chapter-Heading}

## Name Index {#name-index .Chapter-Heading}

----A----

Allais, M., 133, 343

Arntzenius, F., 118, 120

Arrow, K., 283, 294, 295, 296

Ayer, A. J., 2, 3, 14, 15, 16, 24--33, 150, 315

----B----

Bacchus, F., 53, 54

Barker, S., 31

Bateman, B., 14, 206, 301, 313, 314, 315, 316

Bertrand, J., 86, 198

Bigelow, J., ix, 149, 167

Black, M., 23

Blackburn, S., 24, 29, 32, 33

Borel, E., 75, 201

Broome, J., 118

----C----

Carnap, R., vi, 1, 2, 17--28, 35, 36, 137, 138, 139, 142, 143, 145, 148, 158, 163, 169, 207, 213, 216, 217, 218, 306, 308

Chase, J., ix

Chisholm, R., 150

Christensen, D., 43, 44, 129, 130

Clinton, W., 240, 241, 242, 244

Cohen, L. J., 245

Collins, J., 167

----D----

Davidson, B., 56, 57

Davidson, P., 321, 322, 336, 337, 339

Davis, J., 14, 313

de Finetti, B., 6, 23, 24, 25, 33, 34, 35, 36, 41, 53, 115, 116

Dempster, A., 87, 90, 103, 104, 111, 245, 294, 295, 298

Dodgson, C., 268

Dummett, M., 43, 182, 186, 187, 188, 248, 269

----E----

Ellsburg, D., 133, 343

----F----

Fagin, R., 95, 96, 108, 110

Fine, K., 171, 177, 186, 190

Fine, T., 17, 100, 302

Fodor, J., 188--96

Freidman, M., 341

----G----

Gardner, M., 86, 87

Geach, P., 30

Gibbard, A., 29, 275

Gilboa, I., 111, 112, 279

Gillies, D., 14, 148, 313

Gillman, L., 122

Glymour, C., 234

Gödel, K., 312, 313

Good, I. J., 42, 59, 81, 83

Goodman, N., 20, 157

Grice, H. P., 146

----H----

Hacking, I., 149

Hájek, A., 5, 279

Hale, B., 32, 33

Halpern, J., 95, 96, 108, 110

Hansson, B., 93, 94

Harman, G., 43, 50, 247

Harper, W., 275

Hart, A. G., 82, 83, 335

Hausman, D., 283

Hempel, C., 236, 317

Hicks, J., 327

Holton, R., ix

Horgan, T., 299

Horwich, P., 30

Howson, C., 20, 24, 25, 71, 129, 130, 207, 217, 218, 219, 220

Humberstone, I. L., ix

----J----

Jaffray, J., 281, 282, 325

Jeffrey, R., 20, 22, 81, 95, 96, 97, 199, 228, 229, 233, 234, 235, 294, 301

Jones, R., 336

----K----

Kahnemann, D., 41

Kaplan, M., 129, 131, 160, 216

Keynes, J. M., vi, vii, 1, 2, 14, 17, 20, 24, 27, 28, 35, 36, 38, 81, 137, 156, 159, 164, 198--214, 221, 273, 300--345

Knight, F., 81, 82, 83, 310, 335

Kolmogorov, A. N., 4, 5, 249

Koopman, B., 59, 74

Kripke, S., 253, 254, 255, 256, 257, 258, 260, 261, 265, 266, 328

Kuznets, S., 338

Kvanvig, J., 43

Kyburg, H., 9, 10, 11, 21, 24, 27, 35, 53, 54, 235--44, 307

----L----

Lawson, T., 310

Leblanc, H., 249, 250, 251

Lepore, E., 188--96

Levi, I., 52, 53, 81, 221--29, 282, 283, 284, 285, 286, 287, 288, 289, 290, 294, 295, 298, 324, 325, 340, 341

Lewis, D., 5, 27, 28, 29, 44, 56, 87, 138, 139, 140, 141, 144, 151, 152, 153, 154, 159--68, 183, 218, 250, 260, 268, 275

Locke, J., 149

Lowe, E. J., 144

----M----

Maclachlan, F., 333, 334

Maher, P., 52, 53, 129--36, 160

Makowski, L., 335, 336

Mares, E., 249, 250, 251

Martin, C. B., 56

McCarthy, D., 118, 120

McCauley, J., 66

McDermott, M., 188

Mellor, D. H., 39

Menzies, P., 167

Morgan, C., 249, 250, 251

Moser, P., 298

Mulder, D. H., 298

----N----

Nolan, D., ix, 147

Norton, J., 278

----O----

O'Donnell, R., 159, 310, 311, 312

Oppy, G., ix

Ostroy, J. M., 336

----P----

Pargetter, R., 56, 57, 149, 167

Paris, J. B., 109

Pearl, J., 89

Pettit, P., ix

Ponsonnet, J-M., 248

Popper, K., 2, 12, 13, 17, 156

Price, H., 30, 31, 175

----Q----

Quine, W. V. O., 144

----R----

Ramsey, F. P., 2, 22, 29, 38--44, 51, 52, 58, 59, 150, 179, 205--16, 268, 273, 287, 300, 301, 308, 312, 313

Rogers, C., 321

Runde, J., 14, 206, 301, 302, 307, 332, 333, 335, 337, 339

Russell, B., 9, 20, 21, 94, 148, 184, 185, 306, 312

Rymes, T. K., 321

----S----

Sainsbury, M., 176, 181

Saul, J., 146

Savage, L., 23, 25, 27, 41, 53, 59, 129, 130, 341

Schick, F., 51, 52

Schmeidler, D., 92, 93, 95, 111, 112, 245, 279

Schmidt, C., 81

Scott, A., 120

Scott, M., 120

Seidenfeld, T., 134, 277, 289

Shackle, G., 245, 248, 267

Shafer, G., 55, 61, 62, 83, 84--91, 103, 104, 109, 111, 114, 129, 130, 148, 149, 245, 246, 247, 249, 294, 298

Shapiro, N., 320

Skidelsky, R., 301, 308, 313

Skyrms, B., 275

Slutsky, E., 46

Smets, P., 294

Smith, A., 46

Smith, C. A. B., 77, 79, 81, 116

Sobel, J. H., 275, 343

Strat, T., 281, 282, 325

Strawson, P., 187, 188

Suppes, P., 100, 102

----T----

Talmont-Kaminski, K., ix

Tarksi, A., 171

Tarski, A., 170, 176, 194

Thalos, M., 53, 54

Tintner, G., 82, 335

Tobin, J., 333

Tooley, M., 21

Townshend, H., 309

Tversky, A., 41

----U----

Urbach, P., 20, 24, 25, 129, 130, 207, 217, 218, 219, 220

----V----

van Fraasen, B., 49

van Fraassen, B., 9, 19, 23, 44, 49, 50, 52, 71, 77, 81, 110, 194, 227, 229--33, 294

von Kries, J., 198

----W----

Walley, P., 62, 77, 100, 101, 103, 113--23

Whitehead, A., 94, 306

Williams, P., 77, 79, 83, 116, 177, 289

Williamson, T., 169, 176, 177, 179, 181, 185, 186, 187, 193, 201

Wittgenstein, L., 212

Wolfenson, M., 100, 102

----Z----

Zabell, S. L., 206

Zadeh, L., 245

## Subject Index {#subject-index .Chapter-Heading}

----3----

3-coherence, 107

----A----

Absolutism, 168

Addition, 138--45, 265

Additivity, 5, 122--23, 164, 243

countable, 5, 6, 124

finite, 5

Ambiguity theory, 153--67

Analyses of probability

conventionalist, 14, 338--44

frequentist, 7

intersubjective. *See* conventionalist

logical, 17--23

modal frequency, 11

necessitarian, 151, 220

partial entailment. *See* logical

propensity, 12--13

reasonable degree of belief, 1, 146--80

subjectivist, 23--37

syntactic. *See* logical

Anti-realism, 141, 267

Arguments for imprecision

ignorance, 79, 212--14

introspection, 78

Levi's, 237--42

rational disagreement, 80, 214--15

vagueness, 215--17

van Fraassen's, 246

Arrow's Theorem, 305, 318

----B----

Basic Chance Principle, 180

BCP. *See* Basic Chance Principle

Belief

is degree of belief one, 67, 170--73

Belief functions. *See* Shafer functions

*Bel*~S~. *See* Shafer functions

Betting analysis, 38, 40--45, 56--59, 78, 83, 107, 109, 138, 144, 145, 171

and constructivism, 266--67

and incoherent agents, 45

restrictions on, 47

----C----

*c*‑functions, 19

Chance, 148--50, 153--67, 173--80

non-numerical, 163, 346

Coherence, 67

closure, 67, 71

consistency, 67, 71

dynamic, 71

justification, 232

Kyburg's objection, 254

Complete monotonicity. *See* monotonicity

Conditionalisation, 35, 63, 64, 71, 74, 75, 77, 84, 113, 115, 116, 117, 123, 162, 236, 238, 242, 243, 247--50, 301, 320, 321

Conglomerability, 109, 120--31, 299, 302

defined, 122

finite, 112

restricted, 299

Constructivist Probability, 141, 264--93

and anti-realism, 267

and betting analysis, 266

and Equivalence Analysis, 268

axioms for, 272

falsum, 270

ignorance, 265

intuitionist probability, 280--84

Kripke trees, 273--84

objections, 288

updating, 284

verificationism, 266

Contextualism, 170--73

Continuity, 245, 296

Conventionalism, 168--70

Conversational score, 154

Convexity, 102, 244--45

----D----

Debts, 349

Decision rules

Caprice, 314--18

conservatism, 311--14

global dominance, 300

Horvitz, 303, 365

Levi's, 304--11, 367

Maxi, 301--4

maximin, 301, 317

Decision theory

defined, 294

Degrees of belief, 60--180

and behaviour, 40

imprecise, 77--131

introspective, 39

precise, 2, 63

qualitative and quantitative, 61

rational-valued, 63

Dempster-Shafer functions. *See* Shafer functions

Dilation, 298

Dispositions, 17, 29, 39, 41, 55, 58, 59, 122, 145, 172, 173, 216, 218, 246, 251, 322

finkish, 58, 172

Disquietude, 368--71

Dutch Book Argument, 2, 24, 38, 44, 45--56, 62, 65, 71, 74, 75, 82, 138--45, 267, 269, 294, 295

and intuitionism, 51

for conditionalisation, 74

----E----

Elliptical references

to evidence, 1

Elliptical terms, 155

Ellsburg paradox, 142

Equivalence Analysis, 60--62, 71, 84, 244, 313

Event defined, 96

Evidence, 1

implicit, 165--67

sentences, 23

uncertain, 230--32

Exchangeability, 34--37

Exclusive disjunction, 69

Expressivism, 29--34

----F----

Families of predicates, 19

Families of probability functions. *See* Models for degrees of belief; Many Models

FH conditionalisation, 115

Figures, 116--18, 247--50

Finkish. *See* Dispositions

Frege point, 31

----G----

Grue, 22, 262

----H----

Horizontal-vertical problem, 9

----I----

Implicature, 156

Independence, 35

Infinite utility, 43

Infinitesimals, 172

Internalism, 151

Intuitionist probability, 43

Intuitionist Probability. *See* Constructivist probability

----K----

Kripke trees, 273--84

interpretation, 281

----L----

Liquidity, 353

and uncertainty, 358

motives, 357

Locke's Principle, 160

----M----

Marginal utility

of money, 38, 53

Mass function, 93

MHP. *See* Monte Hall Problem

Missing markets, 355

Models for degrees of belief

constructivist, 291

imprecise

Fagin-Halpern, 100--102

Many Models, 80--88, 96

Many-Urn, 103

Single Model, 88

updating, 109--19

precise, 65

updating precise models, 71

Money, 349

essential properties of, 353

Monotonicity, 96

Monte Hall Problem, 297, 301, 310, 320--22, 368

----N----

New Principle, 173--80

Non-projectible predicates, 21

NP. *See* New Principle

----O----

Occam's Razor, 156

----P----

Paradoxes of Indifference, 20

Pierino, 50--51

Pignistic Probability, 316

Platonism, 222

Possibility spaces, 100

PP. *See* Principal Principle

Precise degrees of belief, 2

Precisifications. *See* Supervaluations

Preference

axioms for rational preferences, 43

Preferences

axioms for rational, 141

independence, 141

Reduction, 143

transitivity, 141

Principal Principle, 149--50, 173--80, 229

defined, 149

Principle of charity, 154

Principle of Indifference, 62, 79, 212, 222, 228, 265, 330

Probabilistic Disjunctive Syllogism, 129

Probability

axioms, 4

calculus, 3--7, 227

conditional, 4

interval-valued, 246

Probability sentences, 3, 185--88

comparative, 260

relational, 146--50

truth-aptness, 187

Probability~2~, 148

Propositional gambles, 121

Propositions

*de nunc*, 150

simple, 224

subject of probability sentences, 3, 146--48

----R----

Reduction, 313. *See* Preferences

Reference class, 8

Reflection, 50, 54, 71, 72, 73, 130, 246

Relationism, 168

Relativism, 167--70

Risk aversion, 99

----S----

Shafer functions, 92--97

State of confidence, 350

Supertruth, 184

Supervaluations, 181--212

and first-order truths, 205

and models of language, 202--10

and validity, 199--202

global validity, 199

local and general, 210

local validity, 199

moderate, 199

penumbral connections, 183, 205

permutation problems, 206

precisifications, 183

scope ambiguities, 188--99

strong, 199

weak. *See* orthodox

----T----

Three Prisoners Problem, 90--92, 111--12

TPP. *See* Three Prisoners Problem

Truth, 195--99

T-schema, 182, 188--99

Two-envelope paradox, 126--29

----U----

Uncertainty

and money, 348, 351--56

defined, 334

epistemic not aleatory, 346

Keynes's definition, 333

Uncertainty aversion, 97--100

Undermining, 176

Unemployment, 345

Use-value and exchange-value, 46

----V----

Vacuous epistemic state, 101, 124

Verificationism, 15, 266

----W----

Weight of arguments, 326

analysed, 331

and irrelevant evidence, 329
