# Acknowledgments {.unnumbered}

As with any doctoral dissertation, this could not have been completed without supervisory support and assistance. My supervisors, Graham Oppy and Richard Holton, have excised many of the bad ideas from the dissertation and assisted greatly in the development of the good ones. The usual disclaimer about remaining mistakes applies. Graham's diligence in detecting spelling and grammatical errors was probably all that prevented an embarrassing surfeit of errors remaining herein.

I also owe a great debt to the departments I attended while undertaking the degree: the Philosophy department at Monash University and the Philosophy Program in RSSS, Australian National University. In particular, I would like to thank John Bigelow, Lloyd Humberstone, Philip Pettit, Daniel Nolan, James Chase and Konrad Talmont-Kaminski for discussions on subjects in my dissertation, as well as the audiences at several seminars I presented in those departments over the last four years.