# Keynes and Probability {#sec-chap-10}

## 10.1 Introduction {#introduction-4}

I have earlier described the theory defended in this thesis as a Keynesian theory of probability. In this chapter I want to defend that description. The purpose of this is twofold. First, there is some scholarly interest in accurately tracing the ancestry of ideas. Secondly, and more importantly, Keynes thought that his theory of probability led to distinctive theories in economics. I don't think he's right about this, for reasons I'll set out in the next chapter, but my argument turns on the theory of probability defended here being faithful to Keynes's account.

In the next section I'll set out the theory of probability Keynes advanced in his *Treatise on Probability* (1921a), and show how my theory captures the crucial elements of his. In some respects Keynes's theory is internally inconsistent: the detailed rendition does not capture the explicit motivating ideas. The theory here is closer to the spirit of Keynes's approach in these cases than its letter. Whether this is taken as charitable interpretation or friendly revision is probably not very important.

In section three I'll note how Keynes incorporated his philosophical insights into his economics. This will be elaborated in the next chapter, when I look at the details of part of his theory of unemployment. The most important element of this section is a theory of Keynesian 'uncertainty' which there is strong evidence to show he adopted.

There has been much debate in recent years over precisely what theory of probability Keynes was using when he wrote his *General Theory* (1936), and in particular how much the attacks of Ramsey and, perhaps, Wittgenstein had led him to abandon claims he had made in the earlier book. Much of this debate seems to assume that Keynes's early theory was such a tight package that it couldn't be amended without being lost. Hence we have arguments about whether Keynes kept or abandoned his early theory. There is no doubt that he conceded some attacks were justified, but the evidence is consistent with his abandoning no more than a couple of relatively unimportant theses. In the last section I'll look at the claim he adopted a radically different theory of probability, a conventionalist theory. Again I argue the evidence is consistent with no change having occurred, and, a little more tentatively, I argue that it is inconsistent with his having adopted a conventionalist view. For convenience, in what follows I'll refer to the *Treatise on Probability* and *General Theory* as the *TP* and *GT* respectively[^121].

[^121]: Strictly speaking, it wouldn't hurt my story if Keynes had moved to a 'vague subjectivist Bayesian' position as in, say, Jeffrey (1983). This is precisely the position Runde (1994) has him adopt. I don't think a great deal in his economics depends on probability relations being objective, though everything turns on their being vague. Since my story would be hurt if Keynes had made the amendments suggested by others (e.g. Bateman (1996)) a small interpretative detour is justified.

## 10.2 Keynes's Pure Theory of Probability {#keyness-pure-theory-of-probability}

The *TP* was Keynes's first major academic work. An early version of it was submitted as a fellowship dissertation in 1908, and after that was rejected a revised version was submitted in 1909. For various reasons it was not published for 12 years, with again significant revisions being made. Included in these revisions was a long discussion of statistical reasoning which arose from a public debate he had with Karl Pearson about the foundations of statistics. Although there is little evidence of it in his early books, Keynes started working theories about expectations into his economics as early as 1910 (Skidelsky 1983: 208; Keynes 1910: 46-7).

Keynes said hardly anything about probability for 10 years after his book was published. He didn't even make much of an effort to respond to scholars who contacted him about it, with more worldly concerns being pressing. In 1931, he made some passing comments in his review of Ramsey's book. Then in the *General Theory*, published in 1936, and the subsequent debate, he made some references to his theory of probability.

The basis of Keynes's theory is that probability is reasonable degree of belief, and this is a logical, non-numerical relation of 'arguments', which are just ordered pairs of propositions[^122]. The probability of an argument is what it is by virtue of logical laws alone, in just the way that an argument is either valid or invalid by virtue of logical laws alone. Indeed, Keynes thinks that the theory of valid arguments is just a special case of his theory of probable arguments, an argument being valid just in case it has probability one.

[^122]: By non-numerical I don't mean that it never takes numerical values, just that sometimes it does not.

Not only are these probability values non-numerical, they are not always comparable. Probability is a non-linear as well as a non-numerical relation. In Keynes's terminology, the probability of an argument could be α, where α is a non-numerical degree of belief, comparable to some but not all numerical degrees of belief and to some but not all non-numerical degrees of belief. However, he says nothing about what type of entity α must be to have these properties. Because of this some later writers (eg T. Fine (1973), Runde (1994a)) have thought that Keynes's theory was best classified as a theory of comparative probability. In one sense it isn't, because it does make sense to talk about the probability of an argument being equal to some number, not just to compare the probabilities of different arguments. However, in a more important sense they are correct, because we know nothing about entities like α -- which are the value of probability relations -- except how they enter into comparisons. It seems that saying the probability of an argument is α is just shorthand for saying which comparisons between it and other probabilities are true.

Keynes might dispute this last analysis. He does develop a rather sophisticated calculus of these values, which impressed some rather distinguished logicians at the time. However, this calculus gives little insight into the nature of the values. As I remarked in @sec-chap-6, when we derive α + β = χ in a Keynesian system, where the Greek characters refer to the values of probability relations, there is no guarantee that '+' means what we mean by *plus*. In the absence of such a guarantee, or a more comprehensive analysis of what such derivations mean, it seems perfectly fair to classify Keynes's theory as comparative.

The other distinctive feature of Keynes's theory, and possibly the one which has aroused the most interest in the subsequent literature, is his concept of 'weight'. The probability of *p* given *q* tells us, in a sense, how the evidence *q* is balanced between *p* and ¬*p*. Keynes thought it might be important in some contexts, particularly decision making, to know not only how the evidence was distributed, but how much of it there was. Thus for every argument he postulated not only a probability, but also a 'weight', which is intended to be a measure of the comprehensiveness of the evidence. If this all sounds a bit vague, it is because the original is just as vague.

> As the relevant evidence at our disposal increases, the magnitude of the probability of the argument may either decrease or increase, according as the new knowledge strengthens the unfavourable or the favourable evidence; but *something* seems to have increased in either case, -- we have a more substantial basis upon which to rest our conclusion. I express this by saying that an accession of new evidence increases the *weight* of an argument. New evidence will sometimes decrease the probability of an argument, but it will always increase its 'weight' (*TP*: 77, italics in original).

Keynes modifies this slightly, saying strictly irrelevant evidence does not increase the weight of our argument. Finally Keynes introduced a new notation, which he thought essential to the progress of the subject. Given the lack of popularity of his notation, and the progress in the theory of probability since his time, his predictive skills seem to have failed here. However, for expository purposes, it is sometimes convenient to adopt his notation. The essentials are to use *p* / *q* = α to mean the probability of *p* on evidence *q* is α, where α may, but need not, be a real number, and to use *V*(*p* / *q*) = β for the weight of the argument from *q* to *p*.

The rest of this section aims to show how the theory of this dissertation captures the essential elements of Keynes's theory. Some parts of the translation are straightforward. Let P be the set of all reasonable probability functions. Then the set *P* of values which *Pr*(*p* \| *q*) takes, for *Pr* ∈ P corresponds in a straightforward way to Keynes's non-numerical degrees. These sets are sometimes comparable with numbers. For real *x*, we say *P* \> *x* iff for all elements *y* of *P*, *y* \> *x*. And this holds if we replace '\>' throughout with '=', '\<', '≥' or '≤'. And sometimes the degrees cannot be compared with a real, as when none of these happen. Similarly the sets can sometimes be compared with each other, and sometimes not. Using Keynes's notation, *p* / *q* \> *r* / *s* iff for all *Pr* ∈ P , *Pr*(*p* \| *q*) \> *Pr*(*r* \| *s*). Again this holds if we replace '\>' throughout with any other comparative. And since it is possible that no such comparative sentence is true, probabilities can be incomparable. Finally, we can now add probabilities in a way that makes it clear we are using the ordinary concept of addition. *p* / *q* + *r* / *s* is the set {*x*: ∃*Pr* ∈ P : *Pr*(*p* \| *q*) + *Pr*(*r* \| *s*) = *x*}. A similar definition applies to multiplication and division[^123].

[^123]: For some purposes it might be better to translate *p* / *q* as a function from P to \[0, 1\], which takes every *Pr* to *Pr*(*p* \| *q*). Then the talk of equality, inequality, incomparability, addition and multiplication is interpreted just as we ordinarily would for functions. For example where *f* and *g* are functions with a common domain *f* \> *g* iff for all *x*, *f*(*x*) \> *g*(*x*), and so on for the other definitions.

So far the connection seems quite close. Since the membership of P is non-contingent I almost capture Keynes's idea that the value of *p* / *q* can always be determined by logic. As I showed in @sec-chap-1, there are good grounds for parting with Keynes on this point, but not for going all the way to subjectivism. A bigger departure comes with the translation of weight.

Keynes's explicit pronouncements about the weight of arguments are inconsistent with his notation and with the underlying idea behind his concept. I think both problems arise because Keynes says that even though *p* / *q* =  *r* / *q*, V(*p* / *q*) might be different from V(*r* / *q*). The analysis of weight I will adopt denies this, and thus avoids the pitfalls that beset Keynes.

The notational flaw first. By representing the weight of the argument from *q* to *p* as V(*p* / *q*), Keynes writes as if weight is not a two-argument function, with arguments *p* and *q*, but a one argument function, with the argument *p* / *q*. Recall that *p* / *q* is Keynes's notation for what I'd write *Pr*(*p* \| *q*). This confusion in evident at the top of page 79 of the *TP* where Keynes says "Let us represent the evidential weight of *the* argument, whose probability is *p* / *q*, by V(*p* / *q*)" (my italics). Taken literally this seems to assume that there is only one argument with probability *p* / *q*, that is the one from *q* to *p*. Since this can't be right, the most natural reading of this sentence is to replaced the italicised 'the' with 'any'. Alternatively, we should write the weight V(*p*, *q*).

The problem is not, however, just a notational one. There is an argument that arguments of equal probability should have equal weight, something which Keynes denies. The problem arises because of disjunctive evidence.

One of the reasons Keynes wants to say that arguments of equal probability can have different weights is because he thinks that when *p* / (*q* ∧ *q*~1~ ∧ *q*~2~) = *p* / *q*, but not *p* / (*q* ∧ *q*~1~) = *p* / *q*, then V(*p* / *q* ∧ *q*~1~ ∧ *q*~2~) \> V(*p* / *q*). This follows from his strict principle of irrelevance. Information *q*~3~ is strictly irrelevant to the argument from *q* to *p* iff there is no conjunction *q*~1~ ∧ *q*~2~ such that *q*~1~ ∧ *q*~2~ is logically equivalent to *q*~3~ and it isn't the case that *p* / *q* ∧ *q*~1~ = *p* / *q*.[^124]

[^124]: This is to be distinguished from *p* / *q* ∧ *q*~1~ ≠ *p* / *q*. By the formal definitions of comparatives I've given, that would only be true if for all *Pr* ∈ P , *Pr*(*p* \| *q* ∧ *q*~1~) ≠ *Pr*(*p* \| *q*). The expression in the text is intended to be true just in case this holds for some *Pr* or other. If the theory of @sec-chap-5 is correct, the two expressions have identical semantic content, but different conventional content. That, of course, is enough to communicate the relevant point!

This move to a strict principle of irrelevance appears to make it impossible for Keynes to ever say that a proposition is irrelevant to an argument. Let *q*~3~ be any proposition such that *p* / *q* ∧ *q*~3~ = *p* / *q* and *q*~3~ is in an intuitive sense irrelevant to the argument from *q* to *p*. For example, let *p* be the proposition that the die I am about to roll will land with six facing up, *q* be the background evidence, and *q*~3~ be that it is now raining in New York. Now the extra evidence is divisible into two components *q*~3~ ∨ *p* and *q*~3~ ∨ ¬*p*. The conjunction of these components is logically equivalent to *q*~3~, and each of them appear to be relevant pieces of information. Unless *q*~3~ / *q* = 1, *p* / *q* ∧ (*q*~3~ ∨ *p*) \> *p* / *q*. So it seems by Keynes's test, whether or not it is raining in New York is relevant to whether or not this die will land six. This information is relevant just because it is divisible into relevant components. Keynes notes this general move when discussing the principle of indifference on page 65 of the *TP*, but doesn't pick it up here. Carnap (1950: 420) seems to be the first to note that Keynes's strict concept of irrelevance is degenerate for the reason listed here.[^125]

[^125]: It seems quite amazing that no one picked this up before Carnap. Whitehead read the *TP* twice as one of Keynes's fellowship examiners, and Russell presumably read it closely before giving a strong endorsement of its formal work in Russell (1922). And while the other logicians with whom Keynes was in contact weren't in the same class as Russell and Whitehead they were still quite proficient. And Keynes notes that this decomposition of a proposition causes some difficulties for his rendition of the Principle of Indifference just five pages after he states the strict principle of irrelevance.

What is less frequently noticed in the Keynes literature is that the strong theory of irrelevance is central for Keynes's theory of weight. We are trying to find out whether or not *p*, and our current information is *q*. Assume that the strict concept of irrelevance is inapplicable when evaluating weight, so there is some information *q*~1~ which is irrelevant, but which is divisible into relevant components. The weight of our belief in *p* (i.e. the weight of the argument from our evidence to *p*) will be unchanged if we find *q*~1~, as it is irrelevant. However, if we discover *q*~1~ by discovering its components sequentially then, if weight increases upon the acquisition of relevant evidence, the weight of our belief will have risen. So the weight of our beliefs will depend not just on what our evidence is, but on the order in which we acquired it. This is absurd, so it must be that weight doesn't always increase upon acquiring relevant evidence, and may in fact decrease.

This argument reinforces the intuitive idea that when *p* / *q* = *r* / *s* then V(*p* / *q*) = V(*r* / *s*). The analysis of weight in my theory does this, as well as capturing I hope the spirit of Keynes's theory, although it departs radically from the letter of it[^126]. Let P again be the set of values that *Pr*(*p* \| *q*) takes for *Pr* ∈ P . Then P will be an interval, and V(*p* / *q*) is simply the one less length of that interval.[^127] As noted in the last chapter, the possibility of dilation means that we might be certain that on reception of the result of a trial (i.e. learning *q*~1~ or learning ¬*q*~1~) the weight of the argument from our evidence to *p* might go down.[^128] This is odd, but considerably less odd than the alternatives. It is a consequence of my analysis of weight that when we know the chance of *p*, the weight of our argument to *p* is maximised. As we'll soon see, this is a position which Keynes adopted when he applied his theory to economic matters in the 1930s.

[^126]: There is a sense in which my departure from 'what Keynes really meant' isn't that great. If we adopt semantic externalism, then Keynes's references to 'weight' will refer to whatever it is in the world that best satisfies his descriptions of the role it plays. And that, I am confident, is what I have captured. Similar remarks will apply to 'probability' and other terms. Such an interpretation takes Keynes's intention for his referring terms to have referents more seriously than his particular description of those referents.

[^127]: A similar suggestion for capturing this concept is made in Kyburg (1961: 225), though the interval in question has a somewhat different meaning in his theory.

[^128]: This is also a consequence of the quite different analysis advanced in Runde (1990). He suggests we analyse weight as the ratio of known to unknown evidence, then immediately gives this an epistemic interpretation, so that weight becomes a ratio between how much we know and how much we know we don't know. Since new evidence might show that there is even more evidence we don't know, weight might go down with new evidence. I don't see, however, what the grounds are for the epistemic turn here; weight in Keynes seems to be objective enough that there could be a divergence between its value and our best estimate of it.

## 10.3 Keynes's Applied Theory of Probability {#keyness-applied-theory-of-probability}

Since the publication in 1983 of the first volume of Skidelsky's biography of Keynes there has been a surge in interest in Keynes's philosophy. A large motivation for this is the possibility that Keynes's philosophical beliefs play an important role in his economic theories. Like all modern economists, Keynes was aware of the role of expectations in determining the value of goods. Whenever we consider deferring consumption today in the hope of greater consumption tomorrow, our decision will depend crucially on our expectations of what tomorrow will be like; on our partial beliefs about tomorrow. The story is in fact a little more complicated. Since tomorrow we might decide to defer consumption again, it also depends on our expectations about two days time, and hence about three days time, and so on.

Here there is obviously a role for some theory of probability. However, many theories of probability fail to capture an important fact about this decision situation. We know more about tomorrow than about next year and more about the next year than the next decade. Keynes can represent this by saying that the weight of the argument from our evidence to propositions about tomorrow is greater than that of the argument from our evidence to propositions about next year. However, there is no way in which theories which say our degrees of belief ought be precise can do this. This applies whether the theories are subjectivist (like Ramsey) or logical (like Carnap). So Keynes has extra resources to bring to this problem, and he uses them.

> It would be foolish, in forming our expectations, to attach great weight to matters which are very uncertain. (In footnote:) By "very uncertain" I do not mean the same thing as "very improbable". *Cf*. my *Treatise on Probability*, chap. 6, on "The Weight of Arguments". (*GT*: 148)

He elaborated on this in a famous passage from a 1937 article responding to critics of his theory.

> By 'uncertain' knowledge, let me explain, I do not mean merely to distinguish what is known for certain from what is only probable. The game of roulette is not subject, in this sense, to uncertainty; nor is the prospect of a Victory bond being drawn. Or again, the expectation of life is only slightly uncertain. Even the weather is only moderately uncertain. The sense in which I am using the term is that in which the prospect of a European war is uncertain, or the price of copper and the rate of interest twenty years hence, or the obsolescence of a new invention, or the position of private wealth holders in the social system in 1970. About these matters there is no scientific basis on which to form any calculable probability whatever. We simply do not know. (1937a: 113-4)

Finally, in some 1938 he indicated the effect this uncertainty might have on decision theory. The context is a letter he wrote to Hugh Townshend, a former student, who appears to have been the first to inquire about the connection between the *TP* and *GT*.

> One arrives presumably at the numerical estimates \[of expected values\] by some system of arranging alternative decisions in order of preference, some of which will provide a norm by being numerical. But that still leaves millions of cases over where one cannot even arrange an order of preference. When all is said and done, there is an arbitrary element in the situation. (1938a: 289)

O'Donnell (1991) claims there are obviously distinct senses of uncertainty underlying these three quotes. Call these the 1936, 1937 and 1938 senses, by reference to the year from which the quote is drawn. I doubt that there are such distinct senses in play. There is a simple concept of uncertainty which can perform all the roles Keynes asks of it, and so the simplest explanation of the data is that Keynes was using that concept.

'Uncertainty' has been distinguished in economics from pure risk (such as we face at the roulette table) ever since Knight's *Risk, Uncertainty and Profit* (1921). However, Knight's distinction was based on a frequentist theory of probability, so it isn't overly important here. Say that *p* is uncertain for an agent with evidence *q* iff *p* / *q* is non-numerical[^129]. More generally, say *p* is more uncertain the smaller the weight of *p* / *q*.[^130]

[^129]: Or in the functional terminlogy of footnote 123, if *p* / *q* isn't translated to a constant function. This suggestion first appears in Lawson (1985).

[^130]: I.e. if *x* and *y* are the greatest and least values respectively such that *x* ≤ *p* / *q* ≤ *y*, the uncertainty of *p* is measured by *y* ‑ *x*.

Since non-numerical probabilities are usually associated with having little evidence, this captures the 1936 sense of uncertainty[^131]. The examples from the 1937 quote seem to match my definition, at least given some plausible assumptions about when the probability of *p* would be numerical. I also suspect we can translate 'calculable' from the last line as 'numerical'. Finally, non-numerical probabilities will easily lead to non-comparable goods. Say the probability of *p* is vague over \[*x*, *y*\], with *x* \< *z* \< *y*. Then a *p*‑bet will be incomparable with *z* cents. Further, incomparability (as compared to indifference) can't arise without this type of uncertainty.

[^131]: There are counterexamples, as in Monte Hall type cases, but we can be very confident that Keynes was ignorant of these. And we can be confident that these don't threaten the claim in the text as to what is 'usual'.

As there is a simple sense of uncertainty which is definable in straightforward terms (indeed the definition uses no terminology not in Keynes) and which does the work needed for all three quotes, I disagree with O'Donnell's claims that Keynes was using uncertainty differently every time. The main difference between our interpretations is that O'Donnell thinks the 1937 quote relied on the 'unknown probabilities' which are also introduced in the *TP*. We can all be ignorant of logical entailment relations. 'Snow is white' entails (at least on traditional definitions of entailment) Fermat's Last Theorem, but most of us were ignorant of that until very recently. Similarly, thought Keynes, we can be ignorant of logical probability relations. O'Donnell claims this is what is being referred to in the last line of the 1937 quote. He is forced to make the (empirical) claim that we are more often ignorant of these relations when the evidence is small, and he does this. The first problem with O'Donnell's position is that it is hard to see what the evidence for this could be. I am quite certain of the probability of 'My carpet is blue' given just 'Snow is white'; it is represented in my terminology by the interval \[0, 1\]. The second is that given the audience for this paper (it was printed in the *Quarterly Journal of Economics*) it would be unusual to base one's theory on the logical shortcomings of agents. I agree with O'Donnell that these shortcomings are hardly sufficient to say Keynes's agents are 'dim-witted', but I still think it would be an odd assumption for Keynes to make in that forum without more explicit acknowledgment. The third problem for O'Donnell's interpretation is that it seems to make uncertainty an 'on-off' property, rather than one admitting of degrees, as in my account. Yet Keynes's examples show he intended uncertainty here to come by degrees. Even if none of these arguments work, on general methodological grounds I prefer my interpretation because it is the simplest one that explains all the data.

There is a more important question on which I am in almost complete agreement with O'Donnell. In his (1989) he puts forward the most sustained defence of the position that Keynes's philosophical outlook was, in broad terms, unchanged throughout his life[^132]. This is despite the evidence that Keynes adopted a conventionalist epistemology (which I'll discuss in the next section) and that in his 1931 review of Ramsey's book he appears to yield to Ramsey on some crucial questions. I am in general agreement with O'Donnell on these points and there is little need here to repeat his arguments. There is however one point on which I do think Keynes abandoned the *TP* position, and this may explain Keynes's apparent yielding to Ramsey on some points.

[^132]: The different senses of uncertainty aren't a change of view on O'Donnell's theory, they are different facets of a multifacted concept.

In the review of Ramsey, Keynes notes how the scope of logic, which looked so broad under Russell and Whitehead, was gradually reduced by Ramsey and Wittgenstein until it looked like logic had no content at all. I think this is a sign that Keynes abandoned the position that his probability relations were logical. He didn't give up on their objectivity, he just now thought there were objective standards of rationality that were extra-logical. These objective standards, as opposed to logic, would provide the foundations of probability. Without going for a line-by-line exegesis, I'll just note that Keynes's text supports the claim that it was on this point that Keynes yielded to Ramsey.

That much seems quite well grounded; what follows is rather speculative. A year before Keynes's review of Ramsey appeared, Gödel announced his incompleteness theorems. These were widely taken to cast doubt on Russell and Whitehead's program of incorporating all of maths into logic. If Keynes knew of this result and that reaction (which is at least possible, but is hardly certain) this might have convinced him there were objective epistemic norms (i.e. conformity with mathematical reasoning) which were not strictly logical, and this would have made his abandonment of the claim his probability relations were logical less dramatic. There is no reference to Gödel in Keynes's review, which might look like evidence against my speculation that he was influenced by Gödel on this point, but on the other hand there is no reference in it to anyone at all outside Cambridge!

This isn't intended as a criticism of theorists who say that Keynes's theory of probability was little changed over his life. I suspect that, from Keynes's point of view, this was a little change. Another little change he may have made was dropping the view that his probability relations were non-natural[^133]. The difficulty facing all sides in this debate is that Skidelsky's summary of Keynes's later view seems unimpeachable: "\[After 1921\] Keynes no longer thought about probability, though probability permeated his thought." (Skidelsky 1992: 73) If Skidelsky's right, then the correct approach is what I've adopted. The only role for probability in Keynes's later thought is in application.

[^133]: I wonder if he might have been convinced they were not by Ramsey's analysis of theoretical terms (Ramsey 1929a). This could be pressed into giving a naturalist reading of apparently non-natural terms, but I rather doubt Keynes would have seen this, or even considered it an interesting object of study compared to his other projects at the time.

## 10.4 Keynes and Conventions {#keynes-and-conventions}

Many authors argue that Keynes adopted a conventionalist, intersubjectivist theory of probability. See, for example, Bateman (1996), Davis (1994), and Gillies (1988). I'll focus on Bateman's account, as it's the most comprehensive and most recent. It isn't always obvious what is meant by such a theory. In particular, it isn't clear whether it is meant to be an empirical or a normative theory; whether Keynes is apparently claiming that we ought set our partial belief by convention or that we in general do. Since the empirical theory would be consistent with his objectivist norms, and stress is on the change in his views, I conclude that the claim is that this is a new normative view. According to this view, being reasonable is analysed as conforming to conventions; this contrasts with the *TP*'s position that being reasonable involves just making reasonable judgements in particular cases. This is not a very standard epistemological position, but something similar is often endorsed in ethics. In ethical language, it is a move from an act-based to a rule-based epistemology. Bateman marshals the evidence that Keynes moves from an objectivist to a conventionalist position in ethics as evidence for this epistemological shift, but this doesn't seem of overwhelming significance[^134].

[^134]: If Keynes had adopted a framework which implied a tight connection between epistemological and ethical norms, such as utilitarianism, this would be important, since he couldn't change ethics and keep his epistemology. But such frameworks aren't compulsory, and, given the vehemence with which Keynes denounced utilitarianism (Keynes 1938b, 445), it seems he didn't adopt one. Further, there is substantial evidence that, by the time the *TP* was completed, Keynes had already adopted a rule-based ethics as in effect a response to the war. See Keynes (1921b: 298) for the most compelling such evidence. Hence there was no connection in Keynes's mind between ethics and epistemology on this point.

Here's the closest Bateman gets to a definition of what he means by an intersubjective theory of probability.

> When probabilities are formed according to group norms, they are referred to as intersubjective probabilities ... I take it to be the case that in a world of subjective probabilities some individuals will form their own estimates and others will form them on the basis of group norms (50n).

This makes it look very much like an empirical theory, since it refers to how people actually form beliefs, not how they ought. So his intersubjectivism looks perfectly consistent with Keynes's objectivism. I am completely baffled by the 'world of subjective probabilities'. I wonder what such a world looks like, and how it compares to our world of tables, chairs and stock markets?

Fortunately there is a theory which does the work Bateman needs. Ayer (1936) rejects orthodox subjectivism about probability on the grounds that it doesn't allow people to have mistaken probabilistic beliefs. But he can't admit Keynesian probability relations into his sparse ontology. The solution he adopts is to define probability as degree of rational belief, but with this caveat.

> Here we may repeat that the rationality of a belief is defined, not by reference to any absolute standard, but by reference to part of our own actual practice (Ayer 1936: 101).

The 'our' is a bit ambiguous; interpreting it to refer to the community doesn't do violence to the text, though it is just as plausible that it refers to a particular agent. The 'part of our practice' referred to is just our general rules for belief formation. These aren't justified by an absolute standard; they are justified by the fact they are our rules, and presumably by their generality. Given Bateman's views about metaphysics[^135], it seems quite reasonable to suppose he'd follow Ayer on this point.

[^135]: He thinks that 'analytic philosophy is the last place one would expect to find metaphysics' (Bateman 1996: 39)

The evidence that Keynes adopted such a position is usually taken to be some passages from the *GT* and the 1937 *QJE* paper I quoted above. Here's the key points from the two quotes Bateman uses to support his view.

> In practice we have agreed to fall back on what is, in truth, a *convention*. The essence of this convention -- though it does not, of course, work out quite so simply -- lies in assuming that the existing state of affairs will continue indefinitely, except in so far as we have specific reasons for expecting a change (*GT*: 152).
>
> How do we manage in such circumstances to behave in a manner which saves out faces as rational, economic men? We have devised for the purposes a variety of techniques, of which much the most important are the three following: ...
>
> \(3\) Knowing that our own individual judgement is worthless, we endeavour to fall back on the judgement of the rest of the world which is perhaps better informed. That is, we endeavour to conform with the behaviour of the majority or the average. The psychology of a society of individuals each of whom is endeavouring to copy the others leads to what we may strictly term a *conventional* judgement (Keynes 1937a: 115).

There are two problems with using this evidence the way Bateman does. The first is the old one that they seem expressly directed to empirical questions, though in economic writings with their assumptions of rationality such appearances can be deceptive. The more important one is that Keynes is attempting to answer a very specific question with these passages; in ignorance of the question, we can easily misinterpret the answer.

How much ought one pay for a share in company X? Well, if one intends to hold the share come what may, all that matters is the expected prospective yield of X's shares, appropriately discounted, as compared to the potential yield of that money in other uses. But as Keynes repeatedly stresses (*GT*: 149; Keynes 1937a: 113-4) we have no basis for forming such expectations. Were this the only reason for investing then purely commercial investment may never happen.

There is another motivation for investment, one that avoids this problem. We might buy a share in X today on the hope that we will sell it next week (or next month or perhaps next year) for more than we paid. To judge whether such a purchase will be profitable, we need a theory about how the price next week will be determined. Presumably those buyers and sellers will be making much the same evaluations that we are. That is, they'll be thinking about how much other people think X is worth.

> We have reached the third degree where we devote our intelligences to anticipating what average opinion expects the average opinion to be. And there are some, I believe, who practice the fourth, fifth and higher degrees (*GT*: 156).

There is simply no solution to this, except to fall back on convention. That is, we are forced into a conventionalist theory of value, at least of investment goods. But this doesn't mean that we have a conventionalist epistemology. On the contrary, it means that our ordinary (objectivist) empiricism is unimpeded. For the question that Keynes has us solve by reference to convention is, what is the value of X? This is equivalent to, what will be value of X be, or again, to what are the conventional beliefs about X's value? A question about the state of conventions needs answering; and, as good empiricists, we answer it by observing conventions.

An analogy may help here. Here's something that Hempel believed: to gain rational beliefs about the colour of ravens, one has to look at some birds. Did this mean he had an ornithological epistemology? No; he had an empiricist epistemology which when applied to a question about ravens issued the directive: Observe ravens! Similarly Keynes's belief that to answer questions about value, i.e. about conventions, one has to look at conventions, does not imply a conventionalist epistemology. It just means he has an empiricist epistemology which when applied to a question about conventions issues the directive: Observe conventions!

There might be another motivation for using conventions, again consistent with Keynes's objectivist empiricism. Sometimes we may have not made enough observations, or may not have the mental power to convert these to a theory. So we'll piggyback on someone else's observations or mental powers. This seems to be what's going on in the quote from Keynes (1937a). Or even better, we'll piggyback on everyone's work, the conventions. To see how this is consistent with an objectivist epistemology (if it isn't already obvious) consider another analogy.

What is the best way to work out the derivative of a certain function? Unless your memory of high-school calculus is clear, the simplest solution will be to consult an authority. Let's assume for the sake of argument that the easiest authorities to consult are maths texts. It seems like the rational thing to do is to act as if the method advanced by the maths texts is the correct method. Does this mean that you have adopted some kind of authoritarian metaphysics of mathematics, where what it is for something to be correct is for it to be asserted by an authority? Not at all. It is assumed that what the textbook says is correct, but the authoritarian has to make the extra claim that the answer is correct *because* it is in the textbook. This is false; that answer is in the textbook because it is correct. In sum, the authoritarian gets the direction of fit wrong.

Similarly, in the 'piggyback' cases, the intersubjectivist gets the direction of fit wrong. In some circumstances, I might assume that if *p* is 'average opinion', then it is reasonable to believe *p*. But I wouldn't say it is reasonable to believe *p* because *p* is average opinion, as the intersubjectivist does; rather, I say that assuming *p* is average opinion because it is reasonable to believe *p*.

The evidence so far suggests Keynes's statements are consistent with his denying intersubjectivism. I might be able to go further and show they are inconsistent with his adopting that theory. After the quote on *GT* page 152 he spends the next page or so defending the use of conventions here. The defence is, in part, that decisions made in accord with conventions are reversible in the near future, so they won't lead to great loss. If he really were an intersubjectivist, the use of conventions would either not need defending, or could be defended by general philosophical principles. Secondly, there is this quote which in context seems inconsistent with adopting a conventionalist view.

> For it is not sensible to pay 25 for an investment which you believe will yield 30, if you also believe that the market will value it at 20 three months hence (*GT*: 155).[^136]

[^136]: This might be considered odd if we take a market-orientated view of 'yield'. We could plausibly just view the yield of an investment as the value the market will place on it three months hence. Indeed the argument in Chapter 12 of the *GT*, from where the quote is drawn, would support such a view. However, Keynes has made it clear from the context that he intends 'yield' to refer to the real returns of the investment over its lifetime, a question on which a sensible investor can disagree with the market.

The context is that he is discussing why reasonable professional investors base their valuations on convention rather than on long-term expectation. Hence the 'you' in the quote is assumed to be reasonable. Hence it is reasonable, Keynes thinks, to believe that an investment will yield 30, and that conventional wisdom is that it will yield much less. But if all reasonable beliefs were formed by accordance with conventional wisdom, this would be inconsistent. Hence Keynes cannot have adopted a conventionalist epistemology.

