# What Degrees of Belief Aren't {#sec-chap-2}

Ramsey objected to Keynes's view that *probability* means reasonable degree of belief on the grounds that Keynes had provided no explanation of what degrees of belief were. So he proceeded to provide such an explanation, what I'll call the betting analysis. The point of this chapter is to show that Ramsey's analysis can't work, and that even if it did work the Dutch Book arguments based upon it are unsound. With this a major motivation for the betting analysis disappears.

## Analyses of Degree of Belief {#sec-0201}

At his first, and most famous, attempt Ramsey said that having degree of belief *r* in *A* is thinking the bet (1 ‑ *r*, *A*, *r*)[^15] is fair. That is, its expected worth is zero, and an agent who makes this evaluation will be prepared to buy this bet for any price less than zero, or sell it for any price greater than zero. I'll call this the betting analysis of degrees of belief. There is an important qualification to this analysis. I haven't specified in what units the payouts are quantified. If the payouts are quantified in units like dollars with a declining marginal utility, what I'm calling Ramsey's approach won't work. It only works when the payouts are quantified in 'utils' or something equivalent. We can get around this problem in two ways. First, we can follow Ramsey and work out the utility of every possible outcome. Alternatively, we could set the payouts in a good which ought have constant marginal utility. @savage1954a and @smith1961a suggest that lottery tickets have this property, and hence develop their theories using lottery tickets as a currency.

[^15]: The bet (*x*, *p*, *y*) is the bet which pays *x* if *p* and costs *y* otherwise.

There are, however, approaches to defining degrees of belief other than in terms of evaluations of bets and dispositions to bet. Indeed, one of these is set out by Ramsey himself in a later paper. For this approach we have to assume that people can compare, introspectively, their degrees of belief in different propositions. In his earlier paper Ramsey puts forward some arguments against this, but I think these arguments have to fail. To see why we just have to consider Ramsey's arguments carefully.

Ramsey discusses and rejects various possible introspective feelings that could serve as degrees of belief. One of these is 'intensity of feeling' [-@ramsey1926b 169]. Ramsey simply rejects this by an example. We have much more intense feelings about some beliefs which, if pressed, we would admit we believe to a lower degree than those things which we take for granted. For example, in terms of intensity, my belief that 'Lowering tariffs improves welfare' is stronger than my belief 'The earth is round'. On the other hand, my degree of belief in the latter is higher than in the former. Indeed, I suspect my degree of belief that the latter is true is stronger than is my degree of belief that the former is even truth-apt. So my degrees of belief are not mapped by my intensity of feelings. I suspect that for most people we can find examples showing the same effect.

So this particular argument of Ramsey's is effective. But look at what we take as evidence. I simply accepted the introspective evidence that my degree of belief in those things which I take for granted, such as 'The earth is round' is high. Now perhaps even if we didn't have such introspective evidence we could still run Ramsey's argument by looking at the external evidence, such as betting behaviour, to determine our relative degrees of belief in the two propositions. However, I suspect no reader actually did that or anything like it when considering the examples. As Mellor (1980) notes, this point of Ramsey's serves to highlight the pretheoretic plausibility of saying we can introspectively make *qualitative* judgements about our degrees of belief.

This is an important positive argument for the analysis in the next chapter, but it is also a negative argument against the betting analysis. Because Ramsey thinks degrees of belief don't relate to any property determinable by introspection, he thinks that we have to look at what causal impact they have. That is, we have to look at their behavioural implications. Given this the betting analysis seems the most plausible candidate. I agree that if "the kind of measurement of belief with which probability is concerned is ... belief *qua* basis of action" [-@ramsey1926b 171] the betting analysis seems the only plausible approach. However, the above argument, and the existence of the analysis developed in the next chapter, make this premise dubious. The reason the existence of a positive analysis is important is that the early Ramsey denies that there is any 'introspected feeling' which could be measured in the right type of units to be probability. The equivalence analysis shows that we can find such a feeling.

## Why the Betting Analysis of Degrees of Belief Fails {#sec-0202}

Since the definition of degrees of belief in terms of bets is the orthodoxy, I have to show why I think it is untenable before I can justify an alternative outlook. Before going into detail about why I think the identification of degrees of belief with propensities to bet is wrong, I'll simply list the objections:

-   Our propensity to bet is affected by our attitudes towards gambling.
-   Our intuitions about what is reasonable to do on the assumption that the marginal utility of the currency is constant are distorted by our intuitions about everyday situations.
-   On a betting analysis we can't get our probability logic in order until we have worked out our logic of preference, but this has many foundational difficulties.
-   In betting situations there is no operational difference between a proposition being true and its truth being discovered, and if these are significantly different, the betting mechanism will determine our degree of belief in the wrong proposition.
-   The betting analysis presupposes that norms of practice are epistemic norms, but if this is true it is something which must be proven not presupposed.
-   For at least *some* incoherent agents, the analysis looks like it gives the wrong answers.
-   The betting analysis cannot support Dutch Book arguments, as is commonly assumed, and hence does not ground the norms we want, whereas the analysis in this dissertation does ground these norms.

The first objection is a common one, and perhaps not too serious. It has been suggested that we get around this problem by not looking at whether people would bet but rather at which gambles they would accept if offered a choice from a set of desirable gambles[^16]. The latter approach runs into problems of its own because, in cases where agents are susceptible to Dutch Books, the problem won't be the relatively serious one that they can be made to lose money, but the relatively trivial one that they will receive a smaller gift than they could have. Even in these cases, the experimental evidence is that people have a preference for choices which seem to involve less of a gamble, in some undefined and possibly incoherent sense[^17]. The worry is just that these dispositions for or against gambling itself will pollute our information about degrees of belief. Indeed the fact that we can, it appears, sensibly talk about attitudes to gambling polluting the information about degrees of belief seems to count against the idea that we can *analyse* degrees of belief as dispositions to gamble. Certainly attitudes to gambling do not pollute any information we might get about dispositions to gamble. Perhaps though this last point merely shows that the betting analysis is not obviously true, not that it is false.

[^16]: This move is made in @savage1954a [28]. He credits @definetti1937a as the inspiration for it.

[^17]: The experiments I am thinking of are of the following form. Assume we have two goods, *B* and *C*, such that *C* is considerably better than *B* but not overwhelmingly so. If we aren't paying our experimental subjects, *B* could be \$1 million and *C* \$5 million. If offered the choice between a 20% chance of *C* and a 25% chance of *B*, subjects will, on the whole, choose the former. The same choice can be seemingly set up as a two-stage process. Whatever the subjects choose, there is a 25% chance of qualifying for the 'second round'. If they qualify they will receive either *B* for certain or an 80% chance of *C*, but they have to say before they know whether they've qualified which they would choose. Even though this seems functionally equivalent to the first choice, here subjects will overwhelmingly choose *B*, because it doesn't involve a gamble. There is no consequentialist sense in which these choices are coherent. These experiments are reported in @kahnemann1979a [273ff]. They refer to the choice pattern exhibited as 'the isolation effect'. I'll discuss the relationship between dynamic and static choices in appendix 3C and also in @sec-chap-9.

The second objection is related to the first, but it is more pragmatic. Ramsey argues that what we mean when we say a belief is reasonable is that it was formed by a reasonable habit [-@ramsey1926b 194ff]. But what habits are reasonable depends in part on our surroundings. In particular, our reasonable habits may become unreasonable if we are placed in a radically different situation. A similar situation arises in ethics where if we think behaving ethically is behaving in accord with certain sets of rules we have to acknowledge the possibility that in certain unusual situations good actions will have less desirable expected outcomes than bad actions. The objection is that in situations where we are making bets in 'utils' are so different to everyday life that what is reasonable in our situation may be unreasonable in those. Hence our intuitions about what would be reasonable seem unreliable. Since the main point of the betting analysis is to work out what is reasonable, and our basic data is our intuitions about the reasonableness of specific acts, this vitiates the usefulness of the analysis.

On a betting analysis, we work out what degrees of belief are reasonable by looking at what preferences are reasonable. This, however, increases unduly our workload in the foundations of probability. For example, @good1952a notes that we have to work out how to deal with infinite utilities (or show their impossibility) as a foundational task in probability logic on a betting analysis. I don't doubt there are various plausible ways of doing this, but I would prefer my theory of probability was *not* held hostage to a particular analysis of infinity if possible. For a different example, Savage's axioms of preference in his [-@savage1954a] are much more contentious than the probability logic he derived from them. The point is simply the pragmatic one that the less contentious philosophy we have in our foundations the better.

When we place a bet, we don't care directly about whether or not the proposition on which we bet is true. On the contrary, we care directly about whether we and our bettor will come to know that it is true, so we can claim our winnings. So the betting analysis of degrees of belief should lead to our logic of degrees of belief being intuitionist not classical [@harman1983a]. Ramsey gets around this by assuming the bookmaker has the power of the Almighty. It would be distressing if our commitment to classical logic depended on being theists. (There is an interesting comparison here with Dummett's arguments in 'Truth' for the claim that opposing intuitionism requires some kind of commitment to the supernatural.) Even if we accept that it is possible for the bookmaker to have this power, the concern from the last paragraph about the usefulness of our intuitions in these circumstances remains.

It has been pointed out by several authors that Dutch Book arguments grounded on the betting analysis, even if sound, make a large presupposition[^18]. That presupposition is that norms of action, such as 'don't buy Dutch Books', are epistemic norms. Now it may be possible to prove that prudential norms are epistemic; indeed I suspect the analysis here goes some way to proving that. But it is a surprising result, and one for which we ought develop arguments. It isn't something that can be safely supposed, as it appears to be under a betting analysis.

[^18]: For a recent example, see @kvanvig1994a.

@christensen1996a argues for what he calls a 'metaphysical separation' between degrees of belief and betting practices. At one level his argument is an old-fashioned open question argument. Even if we know that someone has degree of belief 0.2 in *p*, we can still ask what evaluations they would make of bets on *p*. Now such arguments aren't particularly telling; it's no refutation of an analysis that it isn't obvious. Christensen, however, has in reserve a somewhat more subtle argument. Assume I will pay 30 cents for the bet (\$1, *p*, 0) but only 20 cents for the bet (\$1, *p* ∨ *q*, 0). My evaluations are, in a sense I will get to, incoherent. The best justification for the betting analysis is that we have to identify mental states by their functional role. If we were to assume the only role a degree of belief plays is in bet-evaluation, there might be a functionalist argument for the betting analysis. As Christensen notes, however, in this case my degree of belief in *p*, whatever it is, performs at least two roles. One is in helping determine how much I'll pay for (\$1, *p*, 0), and the other in helping determine how much I'll pay for (\$1, *p* ∨ *q*, 0). In fact there is a third role; helping determine what my degree of belief in *p* ∨ *q* is. When we're coherent, there will be no tension between these roles. But incoherence, at least of preference, is clearly possible. Christensen's point, I take it, is that for incoherent cases the betting analysis unjustifiably privileges one particular functional role to the exclusion of others, and hence it can be challenged on its own ground.

Finally, one of the advertised strengths of the betting analysis is that through Dutch Book arguments we can provide a justification for degrees of belief obeying axioms of the probability calculus. This was originally argued by Ramsey, and has been extended to dynamic settings by Lewis and van Fraassen. If these arguments succeed they show that the betting analysis has great practical usefulness. However, I show in the next section that these arguments are invalid, or at least unsound. On the other hand, I prove in the next chapter that all the results which Dutch Book arguments claim to achieve can be grounded in a purely epistemic analysis.

## Dutch Book Arguments Fail {#sec-0203}

For simplicity, let's define *the A‑bet* to be the bet (1, *A*, 0), where the unit is of some currency with constant marginal utility and *Bel*(*A*) to be my degree of belief in *A*. The following is a paradigm Dutch Book argument. Assume *Bel*(*p*) is 0.6 and *Bel*(¬*p*) is 0.55. Then, by the betting analysis, I will be prepared to pay *Bel*(*A*) units for an *A* bet, or at least *Bel*(*A*) ‑ ε, for arbitrarily small ε. We'll assume for the sake of the argument that the marginal utility of money is constant in small amounts[^19]. Hence I will pay \$1.15 for a *p*‑bet together with a ¬*p*‑bet. The sum of these bets is ((\$2, ¬*p*, \$1), *p*, (\$1, ¬*p*, 0)) or, in other words, a bet which pays \$2 if *p* and ¬*p*, \$1 if *p* or ¬*p* but not both, and nothing if neither *p* nor ¬*p*. Since it is impossible that *p* and ¬*p* it is impossible that this bet will pay more than \$1, hence my betting practices are normatively flawed. And since by assumption norms of betting behaviour are epistemic norms, I must be irrational. Such arguments can be used to show that my beliefs ought obey all the axioms of the probability calculus.

[^19]: This is a common enough assumption in this field, but I don't see any economic reason for it. If we assume, as is standard, that the utility of any particular level of wealth is independent of our actual wealth, there is no reason to think that the marginal utility of money will be constant around our actual position than it would be around any other positions. If, on the other hand, the marginal utility of money in small quantities really is constant, this leads to problems for orthodox utility theory. I don't want to argue for either of these assumptions and against the other, but it is worth noting that despite the frequency with which each is assumed they are in strong tension.

I agree that if I was prepared to pay 60 cents for a *p*‑bet and 55 cents for a ¬*p*‑bet this would be irrational. That is, I accept for the sake of argument the identification of norms of betting with epistemic norms. However, I don't see how it follows from having certain degrees of belief that I ought be prepared to pay these amounts. The problem is that the argument assumes I will not use any strategic pricing, yet it gives no reason for thinking that I oughtn't price strategically. Indeed it seems implicit in the argument that I ought price strategically. By strategic pricing I mean setting a price for a good that is not determined solely by its intrinsic usefulness, but by how much I could either sell the good for or obtain the good from other sources.

Adam Smith noted some 220 years ago that the price of goods bore no interesting relationship to their usefulness. Nothing is more useful than water, yet it is almost free, nor less useful than diamonds, but they have massive value. We have since learnt that there is in some specified circumstances a determinate relationship between what we'll call the value of a good and its usefulness. If a consumer's budget is at equilibrium then the ratio of the marginal utility of a good to its marginal price will be constant for all goods the consumer purchases provided the utility function of every good is differentiable [@slutsky1915a]. Still, in general, i.e. at disequilibrium, Smith's observation holds. Moreover, since we are assuming that, for the bets in question, the marginal utility of both the payouts of the bets and the currency we use to buy them is constant, unless all people have the same degree of belief in all propositions we can't trade our way to an equilibrium position.

The principle flaw in Dutch Book arguments is that they ignore Smith's observation. My degree of belief in *A* can determine at most the usefulness of an *A*‑bet. Yet it is assumed that it will also determine the price I am prepared to pay for *A*‑bets. Hence it is assumed that there is a correlation between how useful bets are and how much I will or ought be prepared to pay for them. As Smith showed, in general this cannot be the case.

We can find simple examples where it would be unreasonable to pay *Bel*(*A*) for an *A*‑bet. Assume that I know I can sell a *p*‑bet for 90 cents, and *Bel*(*p*) is 0.7. I am offered a *p*‑bet for 80 cents, should I accept? According to the betting analysis I should not, because I am being asked to pay 80 cents for something which has an expected value of 70. However, it seems at least plausible that I should accept the bet and then sell it for a sure profit. Alternatively, assume I know I can buy as many *p*‑bets as I like for 70 cents each in the market, and *Bel*(*p*) is 0.9. Again I am offered a *p*‑bet for 80 cents. The betting analysis says I should accept, but again it's plausible that I should instead buy *p*‑bets at the cheaper market price.

This may not look at first like a major difficulty. After all, we know the correlation between fair prices for *A*‑bets and degrees of belief in *A* only holds under restricted conditions. All these examples show is that we have to be more careful in specifying the initial conditions. As far as it goes, this response is correct. Provided we have good reason to believe that we oughtn't use strategic pricing, the correlation will hold. The problem for Dutch Book arguments is that the only way we can know this is if there is no possibility of later bets, so we can know that we can't buy the bets for less on the market nor make a profit by resale. However, as we saw above Dutch Book arguments in general only work by using retrade. Hence they rely on the correlation between degree of beliefs and betting prices for rational agents holding in a context in which only irrational agents would price bets this way, so the arguments fail.

This conclusion is of major importance for what follows, so I should restate the argument which I have used. Dutch Book arguments rely on there being entailments from agents having certain degrees of belief to their propensity to buy certain bets. They conclude that if some set of our degrees of belief are probabilistically incoherent, we will buy a set of bets which incurs sure loss, and hence we must be irrational. However, the entailment in question only holds under restricted circumstances. One of the restrictions is that there be no possibility for later trade in bets. When there are retrade possibilities, as there must be for most types of Dutch Books to be made, the entailment does not hold. So Dutch Book arguments make inconsistent presuppositions, and hence fail.

It might be objected that if an agent whose beliefs were not coherent with the probability calculus believed falsely that there was no possibility of retrade they would make trades which led to sure loss. However, the only way a bookmaker could exploit this is if she had more knowledge than the agent. And the fact that a bookmaker with more knowledge than us can sell us bets which, given the bookmaker's knowledge, have to lose, is no proof that we are irrational. If it was we would be able to show that any person whose degree of belief was less than 1 for any true proposition, or greater than 0 for any false proposition, is irrational. Moreover, even if we regard such an agent as irrational, it is not clear that it is because her beliefs don't follow the probability calculus that she's irrational. All we can tell from the fact that she will suffer a sure loss is that she's made a mistake somewhere; this might be concerning her misplaced certainty that the market is closed rather than her degrees of belief in the proposition on which bets are placed.

Alternatively, it might be objected that an agent who is completely ignorant of the state of the market will price bets by their expected return even if they think there is the possibility of retrade. The problem with this objection is that it is, famously, very hard to pin down what it is to be completely ignorant. Saying that if I am completely ignorant of whether or not it is the case that *p* then my degree of belief in *p* is, or ought to be, 1/2 leads to well-known contradictions. It certainly would be odd to say that if we are completely ignorant of the likely effects of a certain class of events we should ignore them, which would seem to be the line of attack here. In part 2, particularly in @sec-chap-9, I'll look at various theories about how we ought make decisions under ignorance. Under several of these (particularly maximin approaches) if the agent knows nothing about the market she should make no trades at all rather than pricing according to mathematical expectation. Finally, if the approach advocated in this dissertation is correct and there are necessary probabilities, then in many circumstances an agent is irrational to be completely ignorant in some strong sense. So again, even if the agent is irrational, the Dutch Book argument can't prove that it is the incoherence of degrees of belief with the probability calculus that is making the agent irrational.

In the literature there is generally a distinction drawn between synchronic and diachronic Dutch Book arguments, with the latter being referred to as Dutch Strategy arguments. These latter type are used to infer coherence constraints on how our degrees of belief should change over time. Though the above argument refutes both Dutch Book and Dutch Strategy arguments, the results concerning Dutch Strategy arguments are more striking. Unlike Dutch Book arguments, Dutch Strategy arguments appear to have occasionally led to authors drawing mistaken conclusions.

In his latest argument for a principle called Reflection, van Fraassen discusses the case of Pierino, whom he claims is irrational [-@vanfraassen1995a 11]. Pierino is a young child who today prefers blocks to marbles, but knows that in a year when he has acquired older tastes, he will prefer marbles to blocks. He is in the predicament of today having 9 marbles. Van Fraassen stipulates that Pierino is indifferent between keeping his 9 marbles and trading them for 3 blocks, knowing full well that in a year's time he'll be indifferent between holding these blocks and trading them for a single marble. And this, van Fraassen claims, must be irrational, for if he made the two trades he would have lost 8 marbles. To the obvious response that he will have gained in enjoyment in the short term by having more blocks which he can use now, van Fraassen replies that since he was indifferent to the trades, he can't gain anything.

Van Fraassen's reply makes the mistake we have attempted to highlight here. Pierino's indifference to the trades tells us that at each time the exchange-value of the bundles on offer was equal, but we can't from this infer that the use-value of the two bundles was equivalent. Indeed, assuming Pierino preferred more marbles to fewer in year 2, we must assume that the value of having 3 blocks in year 1 was greater than the value of having 9 marbles, and indeed so much greater that it made up for the expected losses in year 2.

We can make a formal model for Pierino that satisfies these constraints. Assume that U~1~ is the utility he gets from toys in year 1, and U~2~ the utility he gets in year 2. Assume his aim is to maximise U~1~U~2~, and hence that he is indifferent as to the amount of toys he holds at the end of year 2. Let B~i~ and M~i~ be the amounts of marbles and blocks he has in year i, and assume his utility functions are as follows.

> U~1~ = 27B~1~ + M~1~;    
> U~2~ = B~2~ + 3M~2~.

Given that he starts with 9 marbles, if he just holds marbles his net utility across the two years will be 9 · 27 = 243. If he trades the 9 marbles for 3 blocks, knowing that these can only be traded for 1 marble at the end of year 1, his net utility will be 81 · 3 = 243. Hence his indifference to the trade. He could increase his utility if it is possible to trade say 6 marbles for 2 blocks, but we have no reason to assume that that trade is allowed. For reasons I will outline in the next chapter, I think van Fraassen's main conclusion, that all rational agents are Reflective, is sound, but the arguments he uses to get there are mistaken.

One final point ought be noted. When an agent holds a Dutch Book what is important is not that there is no winning outcome. What's important is that all the winning outcomes are impossible. Assume as above that I bought a *p*‑bet for 60 cents and a ¬*p*‑bet for 55 cents. Then if it's the case that *p* and ¬*p* I will win 85 cents, and if it's the case that neither *p* nor ¬*p* I will lose \$1.15. However, in all possible situations I will lose 15 cents. This has two interesting consequences.

First, Dutch Book arguments presuppose a certain logic; in particular one where *p* & ¬*p* is impossible and *p* ∨ ¬*p* is a tautology. There's nothing wrong with this, but it is a presupposition which should be noted. (@harman1983a notes that because of this attempts to use the probability calculus to prove the semantics for natural language ought be classical are question-begging). Unless otherwise stated, I will presuppose classical logic. That is, when I say *A* is impossible I will mean ¬*A* is a classical theorem, and when I say *A* entails *B* I will mean it classically entails *B*.

Secondly, there is a *sound* Dutch Book argument which can be made against a person whose degree of belief in any contradiction is positive, or whose degree of belief in any tautology is less than 1. I'll just illustrate the first. Assume my degree of belief that the four-colour map theorem is false is 0.1. Then I'll buy a bet against it for 5 cents. As there's no possibility of this bet winning, this is a sure loser. And since there's only one bet involved, I didn't assume that retrade was possible, so the above objections to Dutch Book arguments don't apply. The objector who says that it is an *epistemic* possibility that the four colour map theorem is false has a much deeper objection to Dutch Book arguments than I. After all, *p* & ¬*p* might be an epistemic possibility too, so on this approach we could object directly to the toy Dutch Book argument with which I opened this section. Rather than take this road, I will simply assume that in this field we are interested in an epistemology for agents whose beliefs are closed under entailment.

## Other Critiques of Dutch Book Arguments {#sec-0204}

The critique of Dutch Book arguments given here is unique in two respects. First, it is the only one, to my knowledge, to rely on Adam Smith's distinction between usefulness and exchange-value. Secondly, as will be seen in the next chapter I concur with the most famous conclusions of Dutch Book arguments. The usual motivation for criticising these arguments is to motivate dissent with their conclusions. Here the motivation is to provide a cleaner separation of epistemology and decision-theory.

The closest argument in the literature to mine is given by @schick1986a. He argues that Dutch Book arguments fail because they assume that the value of bets is additive. That is, they assume the value of an *A*‑bet is independent of whether or not the agent holds a *B*‑bet. Since bets might be complementary in an economic sense, this is a false assumption, so these arguments fail. This objection is similar to mine in that it relies on a simple economic theory to refute the Dutch Book argument, and because as Schick notes it doesn't apply to 'single‑bet' books [-@schick1986a 116]. However, it is not a successful refutation.

The alleged flaw with Dutch Book arguments on which Schick relies was noted by Ramsey when he originally put the argument. [@ramsey1926b 173-4]. Not only does Ramsey point out the alleged flaw, he notes its prima facie implausibility and offers a small argument to try and defend it. Ramsey claims that when all the final payouts[^20] of all bets are 'ultimate goods', the value of the bets is additive. Now Ramsey's claim here might be wrong, but we should get an argument to this end. Instead, Schick simply assumes that when bets are denominated in utils (equivalently when the marginal utility of money is assumed to be constant) we will get similar economic results to those we'd get were bets denominated in dollars. Schick's mistake (if it is a mistake) is instructive; as I noted above the fact that we don't, even on reflection, have particularly clear intuitions about trading utils is a good reason for not founding our theory of probability on the types of bets Ramsey discusses.

[^20]: When I say the 'final payouts' of bets are of type *X* I mean the following. The set of all bets whose 'final payouts' are of type *X* is the smallest set of bets including all those whose payouts are of type *X* such that any bet such that each of the payouts is a bet in the set is also in the set. If we allow bets to have more than two possible payouts we can amend this last condition accordingly.

@levi1987a and @maher1992a argue that agents who are not Reflective will 'see the Dutch Book coming' and hence refuse to take the bets which lead to being Dutch Booked. Their argument is principally developed to defeat van Fraassen's conclusion that ideally rational agents are Reflective, though it isn't clear why it wouldn't also apply to synchronic Dutch Book arguments. Since it doesn't actually work it isn't particularly worthwhile to speculate how far it would reach were it successful.

The kinds of cases they are thinking of are like the following. Assume I today believe that the probability of *p* is 0.5, and believe that tomorrow I'll believe the chance is 0.3. Assume also I'm offered a *p*‑bet for 40 cents. I know that if I buy it I will be prepared to sell it tomorrow for say 32 cents, for a sure 8-cent loss. That is, I'll be Dutch Booked. But wait! If I see this coming I won't buy the original bet for 40 cents, and thus avoid holding the book. Levi and Maher claim that the availability of this path to unreflective agents blocks the Dutch Book argument.

This response to Reflection fails for the simple reason that being 'Dutch Bookable' is not a necessary condition of irrationality. Assume I don't buy the original 40 cent bet. I won't now be able to sell this bet for 32 cents tomorrow. However, I will still be able to buy a ¬*p* bet for 68 cents. If I take Levi and Maher's advice, I'll have converted a sure loss of 8 cents into an expected loss of 18 cents. There might be an argument to show that this is a rational option, but I'd like to see what it is[^21].

[^21]: The practicalities of this situation are very difficult, and it is impossible to get clear intuitions about what we should do given the assumption of constant marginal utility of money. If I know that tomorrow my degree of belief in *p* will be 0.3, ideally I will take steps to prevent myself acting on this later belief. That is, I should take the Ulysses option. Now buying *p*‑bets today for 40 cents to sell tomorrow at a sure loss will, as is noted in the text, reduce my *expected* loss. However, that is assuming that the number of ¬*p*‑bets I will buy (number of *p*‑bets I will sell) tomorrow is independent of the number of *p*‑bets I buy today. The idea is that taking Levi and Maher's advice *may* in some circumstances, have the effect of tying me to the mast and not trading tomorrow. It *will* have this consequence if the marginal utility of money is not constant, but when it is there are few clear intuitions on the matter.

There is a bigger problem for Levi and Maher's approach. As we saw above, when used by de Finetti and Savage the Dutch Book argument does not require the agent to incur an actual dollar loss. Rather, since the choices are between gifts, the incoherent agent incurs a sure *opportunity* loss. Now when I refuse the original offer of a *p*‑bet for 40 cents, I have already incurred an opportunity loss. Admittedly it is again an *expected* opportunity loss rather than a sure one, but it isn't clear why incurring an expected loss rather than a sure one is an epistemic improvement.

@bacchus1990a run a series of responses to Dutch Book arguments. Their responses to dynamic Dutch Book arguments will be discussed in @sec-chap-3 as possible objections to my arguments for dynamic coherence; here I'll stick to discussing their general comments on Dutch Book arguments. Put in slogan form, they endorse the position that bad betting is bad betting, not bad believing. I agree, but I'm a bit worried about the way they get to this slogan.

Having incoherent degrees of belief (and even the disposition to convert these directly into bets) does not guarantee sure loss. Only this combined with a rather clever and devious bookie does. Note two important consequences of this qualification. First, we now say that certain sets of degrees of belief will not *always* lead to losses, but will sometimes lead to losses. But we knew all along that any degrees of belief (except certain kinds of dogmatic acceptance of only tautologies) *might* lead to losses. Why, we can ask, are the losses caused by devious bookies signs of irrationality, but not the losses caused by taking attractive but ultimately losing bets? I suspect this raises problems for a certain type of pragmatist, but I can't see it as a general problem. The problem isn't that some possibility claim, i.e. we might lose if a certain type of bookie exists, is true, but rather an existence claim, i.e. that a certain type of acceptable but losing bet exists. The second consequence Bacchus, Kyburg and Thalos draw is that the Dutch Book argument only works if we make the paranoid assumption that devious bookies exist. Consistency isn't just the sign of a small mind, but of a paranoid one too. Again, this looks like a good refutation of a certain strictly pragmatic Dutch Book argument. However, we don't need to formulate Dutch Book arguments as strictly pragmatic, and when we don't I suspect this objection loses its force. That is, the possibility of the agent buying a Dutch Book seems at least as great an epistemic flaw as actually making the purchase, and hence anyone who runs a Dutch Book argument is just making an avoidable mistake if they assume an actual pernicious bookie.

## The Betting Analysis as Analogy {#sec-0205}

Although I don't regard the betting analysis as correct, or even that useful generally given the failure of Dutch Book arguments, it may be a helpful analogy. Much of this section is motivated by @shafer1981a, who also regards betting prices as an occasionally useful analogy to degrees of belief, though he's considerably more sceptical than I about the applicability of this analogy. To see when this analogy might be useful, we first have to consider the known limitations on its applicability.

The only way I will use betting examples is to test whether *Bel*(*p*) is reasonable by considering whether it is reasonable to accept or reject offers to buy or sell *p*‑bets. If, for example, in appropriate circumstances it would be unreasonable to reject an offer of a *p*‑bet for 0.2, this can be taken as a good argument for saying that *Bel*(*p*) ≤ 0.2 is unreasonable. First we must consider what circumstances are 'appropriate', or since this seems a bit open-ended, which circumstances are known to be inappropriate. The following have already been mentioned.

-   When the units in which the bet is denominated or traded are of variable marginal utility.
-   When there is a time-delay between when the bet is or would be traded and when winnings would be paid.
-   When there is a possibility of trading in other bets at a later time.

The last is actually a bit broader than what we used above. We have to rule out not just trade in this particular bet, but in other bets as well because some bets are complementary in the economic sense. This is very common in real life. For example, it is worthwhile to buy insurance on your car but not on someone else's despite the fact that the cost of the bets are the same and the expected returns may well be identical (unless say you know you are a worse driver than other people). In part this will be because insurance bets are denominated in a currency with declining marginal utility. However, it seems presumptive to think that complementation is only caused by this effect. Experimental evidence suggests that for many agents the fact that their degree of belief in some propositions is vague leads to a complementation effect. So we have in general to assume this is the last possible trade.

This assumption also gets us around a problem noted by @davidson1985a. Assume I know that your degree of belief in *p* is 0.7, and mine is 0.9. You offer to sell me a *p*‑bet for 0.85. Assuming all other circumstances are in order, this trade will be worthwhile for me. However, I know that if I counter-offer to buy it for 0.71, you will still find the trade worthwhile, and I will have bought the bet for 0.14 less. Davidson and Pargetter thought we could only get around this by assuming the agent under investigation knows the bookmaker has the same degrees of belief as they. However, once we know this is the last chance to bet, i.e. that the counter-offer possibility is closed, we don't need to make this extra restriction, and since we need to have a closed market after the bet in question for other reasons, Davidson and Pargetter's restriction seems redundant.

Even though it is not needed in these cases, however, we might want to restrict attention to cases where each party to the bet is known to have the same information for the following reason. Degrees of belief can at most determine dispositions to bet, not actual betting practices. Even if I have a disposition to buy *p*‑bets for 0.2, if I am offered a *p*‑bet for that price I might not buy. This seems contradictory, but it is not. Dispositions can be finkish [@martin1994a; @lewis1997a]. I might have a disposition to in circumstances *C*, yet be in a situation such that whenever circumstances *C* arise I will lose the disposition.

Assume I have next to no evidence about the players in a certain tennis match, and let *p* be the proposition that the player who serves first will win. Even if I have a disposition to buy *p*‑bets for 0.1, say, if someone were to offer me a *p*‑bet for that price I would most likely refuse. That is, the disposition would be finkish. The reason I would refuse is that the fact I was offered the bet would count as a new piece of information (the information that someone who most likely knows more about the match than I thinks *p*‑bets are worth less than 0.1) and in the state with this extra information I'm not disposed to make the purchase. If I did have the disposition this would be just like paradigm cases of finkish dispositions because the occurrence of the circumstances which are meant to 'trigger' the disposition causes me to lose that disposition in an easily identifiable way.

How could we tell that I originally had a finkish disposition rather than having no disposition at all? The best test seems to be whether I would buy the bet if I knew that the person offering it had the same information I did, and hence that there was little information in the fact that the bet was offered. So the Davidson and Pargetter restriction to circumstances where the offeree knows the offerer has the same beliefs they do is important for cases of complete ignorance to eliminate the effect of finkish dispositions. This will be used in later chapters.

Given these restrictions, it seems the analogy with bets is worthwhile. We will have to be careful to use it only in appropriate circumstances, and to remember that it is only an analogy, and perhaps not the only one. Where possible it will be preferable to use the analysis of degrees of belief to be developed in @sec-chap-3.

